### ISSUE TITLE
Discuss the rules about reply - 回复规则讨论

### ISSUE THREAD

**Issue by introspection3** [polardb/PolarDB-for-PostgreSQL#1]
postgresql社区不缺分布式集群部署机制。

**Comment by raywill** [comment]
Please edit your title in English so that more people can understand you. Thank you!

**Comment by alicloud-qushan** [comment]
We will continue to improve this project, and more innovative technologies such as HLC distributed transactions and plug-in sharding mechanisms will be added in the future. In addition, Alibaba Cloud Database will release more open source products very soon, thanks for your support.

**Comment by Jackarain** [comment]
> Please edit your title in English so that more people can understand you. Thank you!

用中文，没毛病的，除非阿里的人看不懂中文，再说了用中文的人远比用英文的人多。

**Comment by microcai** [comment]
> Please edit your title in English so that more people can understand you. Thank you!

川爸爸没把你收了？

**Comment by yuwei-michael** [comment]
Hi Jackarain  and microcai，语言只是载体，无论用中文还是英文，只要能更好的表达自己的观点就可以，以后如果有人用中文提问，就用中文回复吧。

**Comment by Jackarain** [comment]
@yuwei-michael 平心而论，用中文触动了哪根弦？无非就是一些人觉得英语更有B格而已，装B而已，而且觉得自己的母语低贱。
中文就不能交流吗？所有交流就一定要让老外也能看懂吗？那么老外和老外之间交流，什么时候说为了照顾华人，用中文交流？他们绝不会有半点这种想法。
至少我和中国人说话，不可能要求对面给我讲外语，因为我腿脚不利索，跪不下去。

**Comment by yuwei-michael** [comment]
@Jackarain，开源社区是我们大家一起来维护的，raywill 建议标题用中文，是希望更多人看懂问题，更好的推广和传播我们的社区。我觉得我们的社区是开放的，应该尊重每个人的习惯，无论中文或英文，更好的表达观点才是最重要的。希望大家给Jackarain、raywill、microcai等爱好者点赞！

**Comment by Jackarain** [comment]
@yuwei-michael 是的，我们中国人对老外说外语，实际上这也就是你所说的，尊重他们，才用他们的语言交流。
我们要学习他们的东西，学点外语什么的这也没什么，毕竟他们不可能主动翻译成中文让我们学习。
但这并不代表外语多么的有优越感，如果有这种想法，或表现出这种行为，这是文化极度不自信的表现。
希望有一天，老外来到我们中国，或参与中国人的项目，也希望他们能像我们尊重他们一样，尊重我们，用中文跟我们交流。

**Comment by alienzj** [comment]
> @Jackarain，开源社区是我们大家一起来维护的，raywill 建议标题用中文，是希望更多人看懂问题，更好的推广和传播我们的社区。我觉得我们的社区是开放的，应该尊重每个人的习惯，无论中文或英文，更好的表达观点才是最重要的。希望大家给Jackarain、raywill、microcai等爱好者点赞！

raywill 不是建议标题用中文，恰恰相反，raywill 建议标题用英文。语言是用来交流的，
如果看不懂标题，可以不参与讨论，或者用 google translate;
如果看懂了标题，还要让别人用英文写一遍，那就是故意增加沟通难度了。

Github 从来没有说：Everyone need use english.

特别当你的作品是面向中国用户时，
当然，我们也更希望阿里的作品面向全世界。

**Comment by fanvanzh** [comment]
现在 Chrome 都能自动语言翻译，老外也会用。
老外看我的项目，我都让他们开 Chrome 翻译，不惯他们。

**Comment by LaoshuBaby** [comment]
面对公司的技术军备，不管是真的有用还是重复造轮子

国内公司主导的开源项目确实也已经不少了

面对开源社区所谓的国际化，不管是真的看不懂还是出于恶意

我亦见过面对多国开发者也主动先翻译和研究的社区leader

但，面对精神“贵”族……

只能说……我们无话可说……

**Comment by zopyx** [comment]
English please

**Comment by yuwei-michael** [comment]
Thank you all of your suggestion from Jackarain, microcai, raywill, alicloud-qushan, 564064202, alienzj, fanvanzh, LaoshuBaby, zopyx. We will continue to keep those rules base on our first discuss, the Language is supporter, your opinion is more important, so you can choose your language by your habit. and the reply will follow the quizzer language.

**Comment by microcai** [comment]
> English please

看不懂可以去学，学不了就去印度恒河洗澡。

**Comment by zopyx** [comment]
Translates to "If you don’t understand, you can learn it. If you can’t learn, you can go to India to take a bath in the Ganges River."

Perhaps it would be better to take your PolarDB back to China if you don't care about the basics in open-source?
The language for almost all open-source projects in English. Take it or leave, @microcai 
Obviously you did not understand how open-source works. So move on with your smelly attitude.

**Comment by microcai** [comment]
显然老外也是看的懂的嘛！

**Comment by zopyx** [comment]
@yuwei-michael can you please remove or ban @microcai ? 

This attitude is rude and not acceptable.
Otherwise, I will file an abuse issue with Github directly.

**Comment by yuwei-michael** [comment]
> Translates to "If you don’t understand, you can learn it. If you can’t learn, you can go to India to take a bath in the Ganges River."
> 
> Perhaps it would be better to take your PolarDB back to China if you don't care about the basics in open-source?
> The language for almost all open-source projects in English. Take it or leave, @microcai
> Obviously you did not understand how open-source works. So move on with your smelly attitude.

Hi zopyx, Thank you for your support and your gentleman reply! PolarDB is open community with open mind, we will obey global open source rules and make PolarDB became world-wide open source product.

**Comment by InnerLife0** [comment]
> Translates to "If you don’t understand, you can learn it. If you can’t learn, you can go to India to take a bath in the Ganges River."
> 
> Perhaps it would be better to take your PolarDB back to China if you don't care about the basics in open-source?
> The language for almost all open-source projects in English. Take it or leave, @microcai
> Obviously you did not understand how open-source works. So move on with your smelly attitude.

I have to say we shouldn't judge an entire nation by one person. Though, if I understand my translator right, such inappropriate behavior may negatively expose the project in the eyes of the community. 
Let project owners do some decisions about how OK is to talk here in such way, so we can next do our own decision about the project.

**Comment by yuwei-michael** [comment]
> > English please
> 
> 看不懂可以去学，学不了就去印度恒河洗澡。

Hi Microcai, 我看了您的Github账号介绍，已经是社区老兵了！社区贡献很大，而且有365人Follow了您，很厉害！我们之前讨论的问题是用英文还是用中文，之前也有了基本的结论，如果您还有更多建议，可以回复前面的帖子，继续讨论。但发表观点时，请使用礼貌用语，上述观点已经让群里很多同学感到不适了，包括很多中国朋友和外国友人，我觉的这也违背了您花费大量精力，贡献社区的初衷。再次感谢您的支持！

Hi Microcai, I have look your Github account summary, you are veteran in open source! you have lots of contribution in community, and already had 365 follower, it's amazing!  Our first discuss is about use English or Chinese to reply by default, and you have give lots good suggestion, we are appreciate for that. and base on first discuss, I think we have got basic conclusion, if you still have new idea, welcome reply our topic for more discuss. But all our opinion should use polite expression，and your above wording already make lots our friends feel uncomfortable, it's include lots our Chinese friends and foreign friends. I think that's already disobey your original intention for service and help more people, thank you for your support again!

**Comment by yuwei-michael** [comment]
> > Translates to "If you don’t understand, you can learn it. If you can’t learn, you can go to India to take a bath in the Ganges River."
> > Perhaps it would be better to take your PolarDB back to China if you don't care about the basics in open-source?
> > The language for almost all open-source projects in English. Take it or leave, @microcai
> > Obviously you did not understand how open-source works. So move on with your smelly attitude.
> 
> I have to say we shouldn't judge an entire nation by one person. Though, if I understand my translator right, such inappropriate behavior may negatively expose the project in the eyes of the community.
> Let project owners do some decisions about how OK is to talk here in such way, so we can next do our own decision about the project.

Hi InnerLife0, Thank you for your support and your opinion. I am also feel above reply is rude and make us uncomfortable, and I think that's wording must have some misunderstand for first discuss. hope all of us keep politeness in later discussion. PolarDB is new player for open source, our experience is still not too much, now we see so many friends to take care of us，include lot of Chinese friends and foreign friends. It must help us became better. Hope we are work together to make PolarDB to became world-wide open source product.

**Comment by Jackarain** [comment]
@yuwei-michael 因为你作为该项目的作者表达了你的观点之后，所以我本来不打算在这个issues下多说什么的。是因为遇到了一个有关libpolar_consensus_wrapper.so的问题，所以再次回到这里，看到了这些，我不得不说，@zopyx 的那一句 「English please」是故意的，甚至是不安好心的，因为他明显看懂了我们在说什么，我想说，这种小技俩其实并不聪明，我既然看到了这一点，必须指出来。

**Comment by yu199195** [comment]
PolarDB 没有用吗？ 你这个标题确实有点不合适

**Comment by Akarinnnnn** [comment]
> Please edit your title in English so that more people can understand you. Thank you!

已阅，狗屁不通

**Comment by yuwei-michael** [comment]
> @yuwei-michael 因为你作为该项目的作者表达了你的观点之后，所以我本来不打算在这个issues下多说什么的。是因为遇到了一个有关libpolar_consensus_wrapper.so的问题，所以再次回到这里，看到了这些，我不得不说，@zopyx 的那一句 “English please” 是故意的，甚至是不安好心的，因为他明显看懂了我们在说什么，我想说，这种小技俩其实并不聪明，我既然看到了这一点，必须指出来。

Hi Jackarain, 

感谢大家的热烈讨论，让我受益匪浅！有讨论就肯定会有分歧，这很正常，而且我觉得没有分歧的讨论不是好的讨论！:) 尤其大家语言不通，讨论中可能会产生了一些误解，有些言论可能已经违背了讨论的初衷，我虽然是该项目的作者之一，但我没有权利也没有能力评审谁对谁错，而且大家都是为项目好，刨根问底，纠结对错并不重要。根据之前的讨论，以下几个基本原则看大家是否赞同，有疑问可以提出或补充。

1. 鼓励大家发表观点，但要使用礼貌用语，否则发帖会被删除。
2. 发帖不强制用英语或中文，回复会尽量按照提问者语言进行回复。
3. 根据之前与外国团队沟通的经验，通常要求有任何一个外国人在场，尽量要使用英语沟通，保证大家都参与讨论，也是对对方的基本尊重。但有时大家能力有限，全用英语难度会比较大，讨论的效果也不一定会好。所以我们团队内部发帖或回复会尽量遵从这个原则。

**Comment by Jackarain** [comment]
@yuwei-michael 关于第2条，我看到 @zopyx 他发了一个贴子 https://github.com/alibaba/PolarDB-for-PostgreSQL/issues/22 让你们做二选一，简单来讲，他的意思就是，要么外语，要么滚粗，讲中文很嚣张。

我不知道大家是怎么看待？

**Comment by Akarinnnnn** [comment]
你给他一巴掌就是了，花这么多精力做甚



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月3日(周四) 下午5:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/PolarDB-for-PostgreSQL] 希望阿里开源更有用的东西 (#1)




 
@yuwei-michael 关于第2条，我看到 @zopyx 他发了一个贴子 #22 让你们做二选一，简单来讲，他的意思就是，要么外语，要么滚粗，讲中文很嚣张。
 
我不知道大家是怎么看待？

**Comment by yuwei-michael** [comment]
> PolarDB 没有用吗？ 你这个标题确实有点不合适



> @yuwei-michael 关于第2条，我看到 @zopyx 他发了一个贴子 #22 让你们做二选一，简单来讲，他的意思就是，要么外语，要么滚粗，讲中文很嚣张。
> 
> 我不知道大家是怎么看待？

以上原则希望大家都达成一致，如果有问题和建议也希望大家继续提出来。我刚把我们讨论的原则翻译成英文回复他了，如果同意我们的规则，会让他把不礼貌的东西删除掉。

Akarinnnnn， fanvanzh， microcai 不好意思，你们之前的几条内容用语不够礼貌，先删除了，同时感谢你们的支持。

**Comment by yuwei-michael** [comment]
> PolarDB 没有用吗？ 你这个标题确实有点不合适

Hi yu199195，

感谢您对PolarDB的支持和鼓励，可能您之前也关注过 “阿里云进入全球数据库领导者象限” 的报道吧，今年阿里云数据库，代表国产自研云原生数据库首次进入Gartner全球数据库领导者象限，以下是Gartner对PolarDB的评价：
“阿里云在产品上具备强大的创新能力，其数据库PolarDB已全面应用于零售、电信、物流、金融等多个行业。例如，中国邮政引入分布式数据库PolarDB-X和数据仓库AnalyticDB，在订单业务峰值超过1亿件的情况下，系统平滑稳定运行；中国联通通过PolarDB-X等重构了其核心IT架构，实现对3.6亿用户的无缝“广覆盖”，成为全球最大的云上BSS系统。今年双11，PolarDB再度刷新了数据库处理峰值纪录，高达1.4亿次/秒。” ，此次PolarDB采用按组件开源，是希望大家更多的了解PolarDB产品，后续会开源更多组件和相关产品，希望大家继续支持和鼓励！

https://baijiahao.baidu.com/s?id=1684337507478828782&wfr=spider&for=pc

**Comment by Jackarain** [comment]
libpolar_consensus_wrapper.so 在其它贴子里说到源码还没放出来，有没有计划什么时候开放源码？我看到其中引用了openssl老版本的api，是已经被否决的旧api，建议支持到最新版本openssl，毕竟像‘心脏出血’这种漏洞也都是发生在openssl的老版本中

**Comment by yuwei-michael** [comment]
> libpolar_consensus_wrapper.so 在其它贴子里说到源码还没放出来，有没有计划什么时候开放源码？我看到其中引用了openssl老版本的api，是已经被否决的旧api，建议支持到最新版本openssl，毕竟像‘心脏出血’这种漏洞也都是发生在openssl的老版本中

很好的建议！Poxos 库的代码已经开源出来了，你可以下载最新openssl库，自己编译试试看吧。

**Comment by Akarinnnnn** [comment]
> > @yuwei-michael 因为你作为该项目的作者表达了你的观点之后，所以我本来不打算在这个issues下多说什么的。是因为遇到了一个有关libpolar_consensus_wrapper.so的问题，所以再次回到这里，看到了这些，我不得不说，@zopyx 的那一句 “English please” 是故意的，甚至是不安好心的，因为他明显看懂了我们在说什么，我想说，这种小技俩其实并不聪明，我既然看到了这一点，必须指出来。
> 
> Hi Jackarain,
> 
> 感谢大家的热烈讨论，让我受益匪浅！有讨论就肯定会有分歧，这很正常，而且我觉得没有分歧的讨论不是好的讨论！:) 尤其大家语言不通，讨论中可能会产生了一些误解，有些言论可能已经违背了讨论的初衷，我虽然是该项目的作者之一，但我没有权利也没有能力评审谁对谁错，而且大家都是为项目好，刨根问底，纠结对错并不重要。根据之前的讨论，以下几个基本原则看大家是否赞同，有疑问可以提出或补充。
> 
> 1. 鼓励大家发表观点，但要使用礼貌用语，否则发帖会被删除。
> 2. 发帖不强制用英语或中文，回复会尽量按照提问者语言进行回复。
> 3. 根据之前与外国团队沟通的经验，通常要求有任何一个外国人在场，尽量要使用英语沟通，保证大家都参与讨论，也是对对方的基本尊重。但有时大家能力有限，全用英语难度会比较大，讨论的效果也不一定会好。所以我们团队内部发帖或回复会尽量遵从这个原则。

这一个很合适。
多说一点，选用外语交流时，为了避免因为自己外语水平不佳而引起的问题，可以在文末附上原文。

**Comment by byronyi** [comment]
"How to Use Open Source and Shut the Fuck Up At the Same Time"

**Comment by Akarinnnnn** [comment]
“避免不礼貌用语”这点我可以理解。
毕竟也不是经常泡在这里，多少还不习惯gh的风格

**Comment by yuwei-michael** [comment]
> > > @yuwei-michael 因为你作为该项目的作者表达了你的观点之后，所以我本来不打算在这个issues下多说什么的。是因为遇到了一个有关libpolar_consensus_wrapper.so的问题，所以再次回到这里，看到了这些，我不得不说，@zopyx 的那一句 “English please” 是故意的，甚至是不安好心的，因为他明显看懂了我们在说什么，我想说，这种小技俩其实并不聪明，我既然看到了这一点，必须指出来。
> > 
> > 
> > Hi Jackarain,
> > 感谢大家的热烈讨论，让我受益匪浅！有讨论就肯定会有分歧，这很正常，而且我觉得没有分歧的讨论不是好的讨论！:) 尤其大家语言不通，讨论中可能会产生了一些误解，有些言论可能已经违背了讨论的初衷，我虽然是该项目的作者之一，但我没有权利也没有能力评审谁对谁错，而且大家都是为项目好，刨根问底，纠结对错并不重要。根据之前的讨论，以下几个基本原则看大家是否赞同，有疑问可以提出或补充。
> > 
> > 1. 鼓励大家发表观点，但要使用礼貌用语，否则发帖会被删除。
> > 2. 发帖不强制用英语或中文，回复会尽量按照提问者语言进行回复。
> > 3. 根据之前与外国团队沟通的经验，通常要求有任何一个外国人在场，尽量要使用英语沟通，保证大家都参与讨论，也是对对方的基本尊重。但有时大家能力有限，全用英语难度会比较大，讨论的效果也不一定会好。所以我们团队内部发帖或回复会尽量遵从这个原则。
> 
> 这一个很合适。
> 多说一点，选用外语交流时，为了避免因为自己外语水平不佳而引起的问题，可以在文末附上原文。

好的，了解。👍

Byronyi， 不好意思，把你的回复删除了！

**Comment by byronyi** [comment]
https://zhuanlan.zhihu.com/p/376516218

See https://github.com/jaredhanson/passport/issues/467#issuecomment-198496876

**Comment by LaoshuBaby** [comment]
Is it really necessary to conduct such strict speech censorship? Can Alibaba's strict censorship of community discussions really create a good community environment?

**Comment by byronyi** [comment]
> Is it really necessary to conduct such strict speech censorship? Can Alibaba's strict censorship of community discussions really create a good community environment?

It's not censorship. Only government agency that is qualified to carry out "censorship". This is moderating.

If you don't like it, please just go away. Posting hate speech does not make the world a better place.

**Comment by zopyx** [comment]
> please just go away

Github will hopefully remove this project

**Comment by yuwei-michael** [comment]
Sorry Zopyx, I have delete your last reply since it's impolite， Please  reply my comments about your topic, if you have any doubt about that rules based on our early discuss, please let us to know, we can try to fix it and make everyone happy.

**Comment by zopyx** [comment]
Perhaps you want to delete a comment like "If you don’t understand, you can learn it. If you can’t learn, you can go to India to take a bath in the Ganges River."" which is discrimatory against Indians as well 🤔
Anyway...you had your chance...

**Comment by yuwei-michael** [comment]
> Perhaps you want to delete a comment like "If you don’t understand, you can learn it. If you can’t learn, you can go to India to take a bath in the Ganges River."" which is discrimatory against Indians as well 🤔
> Anyway...you had your chance...

Please check again, I already delete several impolite reply early based on your suggestion. and this comments is send by yourself now,  if we agree the rules, all people should obey it. we can't “50 steps laugh at 100 steps”。If you agree it, please delete it by yourself, or I will delete it tomorrow since it's violate our rules.

**Comment by yu199195** [comment]
@yuwei-michael  以我做开源和参与社区的经验来看，你完全可以不用理会这些人。 你的脾气确实比我好多了。

**Comment by yuwei-michael** [comment]
> @yuwei-michael 以我做开源和参与社区的经验来看，你完全可以不用理会这些人。 你的脾气确实比我好多了。

 Hi yu199195, 多谢支持！PolarDB才刚开源，群里这么多人关心我们，展开热烈讨论，我觉得这是好事，便于我们尽快发现问题，指定策略，规避问题。Zopyx 也是非常关心我们社区的，开始一直很绅士的提出来很多宝贵建议，后来是被人的不礼貌行为惹毛了，所以建议大家都耐心点，把规则先定下来，有了规则，后面就不会有更多误会了。希望Zopyx还在，可以看下我们社区讨论建议，给出更多有用的建议。

Hi yu199195, Thank you for your support!  PolarDB is new open source project, so many people take care of us, it's chance for us to find and resolve our issue, just need more patience.  Mr. Zopyx is also very take care our community, he have give lots of good suggestion at beginning very gentlemen. But he is infuriate by some guys, I think if we have rules, those would not happen again. Hope he is still here, and give more suggestion about our common rules for our community discuss.

**Comment by ChoviWu** [comment]
兄弟，我感觉这个老外脾气很冲呀，可能有些评论已经被删了

**Comment by ChoviWu** [comment]
开源不易，给你点个赞

**Comment by InnerLife0** [comment]
There was a lot of hate speech here and I don't want to take any side. Why? 
You may be right ten thousand times in general, but when you rude and impolite you are not right by default. And the fact somebody else talk with you so, don't give you any right to reply in the same way.

There is one proverb.
"Who's smarter? The one who can stop first."

Humaneness is not about nations, language or anything else. Let's not judge everyone by one person. Let us be smarter, say STOP, turn this page and meet a new day with conclusions which was ALREADY done. We don't need to spend our energy for hate speeches or reply to them. Really.

Thank you.
P.S. I cannot translate this message into Chinese because I doubt the quality of the translation. If somebody bilingual can do this, you are welcome.

**Comment by Jackarain** [comment]
> Perhaps you want to delete a comment like "If you don’t understand, you can learn it. If you can’t learn, you can go to India to take a bath in the Ganges River."" which is discrimatory against Indians as well 🤔
> Anyway...you had your chance...

Hi, @zopyx 

我并不认为 @microcai 有冒犯到你，更没有什么歧视，因为如果你对这个世界足够了解，对印度足够了解，你就会知道，去印度恒河游泳是一件神圣的事情，那是印度教每12年1次的大壶节，才有的机会，因为印度人相信通过在恒河游泳能洗清罪孽。当然，如果你不喜欢或者不认同去印度恒河游泳是一件好事，那你完全可以说不去，没人会强迫你游泳，你不必过多纠结。

另外，我不得不说，你在这里要求所有人都必须使用英语，否则要求github删除该项目，你的这种行为，真的令人十分反感，希望你能停止这种言论。

**Comment by LaoshuBaby** [comment]
> 
> 
> There was a lot of hate speech here and I don't want to take any side. Why?
> You may be right ten thousand times in general, but when you rude and impolite you are not right by default. And the fact somebody else talk with you so, don't give you any right to reply in the same way.
> 
> There is one proverb.
> "Who's smarter? The one who can stop first."
> 
> Humaneness is not about nations, language or anything else. Let's not judge everyone by one person. Let us be smarter, say STOP, turn this page and meet a new day with conclusions which was ALREADY done. We don't need to spend our energy for hate speeches or reply to them. Really.
> 
> Thank you.
> P.S. I cannot translate this message into Chinese because I doubt the quality of the translation. If somebody bilingual can do this, you are welcome.

### Translation 译文

这里有非常多的充满了憎恨的发言，并且我不打算支持任何一方。为什么？
通常，你可能已经做过一万件正确的事情，但是当你粗鄙发言的时候，你已经默认是不占理的一方了，并且事实是别人正在试图和你交流，请不要给自己任何以同样方式怼回去的借口。

老话说得好，“最先停下来的人才是聪明人”。```①```

仁慈和国家、语言或者其他任何事情都无关，让我们不要仅凭个人观点来评判他人。让我们都聪明一点，一起**停下来**，关掉这个页面，然后迎接新的一个争论**已经结束**的一天吧。我们不需要把我们全部的精力都花费在憎恨或者继续回复这些东西上。真的。

谢谢你！
另外，我不能把这段文字翻译成中文，因为我不相信自动翻译的质量。```②```如果有谁同时会中文和英文能翻译一下的话，提前谢谢了。

-----

### Annotation 译注

①但是说实话我没查到这个
②确实如此，谷歌翻译有时候一些“不对味”的地方还是有的，不过日常沟通足够了
③**兄弟姐妹们咱差不多得了，这老外说的挺实诚的，大家明天还得该上学的上学，该上班的上班，散了吧，我之前也不够冷静，中文英文问题一直就是开源社区老辩经了**

**Comment by yuwei-michael** [comment]
> There was a lot of hate speech here and I don't want to take any side. Why?
> You may be right ten thousand times in general, but when you rude and impolite you are not right by default. And the fact somebody else talk with you so, don't give you any right to reply in the same way.
> 
> There is one proverb.
> "Who's smarter? The one who can stop first."
> 
> Humaneness is not about nations, language or anything else. Let's not judge everyone by one person. Let us be smarter, say STOP, turn this page and meet a new day with conclusions which was ALREADY done. We don't need to spend our energy for hate speeches or reply to them. Really.
> 
> Thank you.
> P.S. I cannot translate this message into Chinese because I doubt the quality of the translation. If somebody bilingual can do this, you are welcome.


Hi InnerLife0, I am full agree your opinions, all debate is stop already. I know the power of philosophy now. I think original intention of all guys is good, but we don't familiar about communication in cross-culture, cross-language. it's make some misunderstanding, after this sufficient discuss, we have reach an agreement about the rules in our group discuss. I think similar misunderstanding will wouldn't happen again. hope we can meet our best friends here through more cooperation. Thank you LaoshuBaby help us to translate this speech! 😀

InnerLife0, 您好，很赞同您的观点，一切争论都停止了，现在了解哲学的力量了！其实大家的初衷都是好的，但对于跨国文化和语言方面的沟通还不熟悉，出现了一些误会，经过充分讨论，我们已经规范了群里的讨论规范，类似情况以后应该不会再发生了。通过后续的合作，希望大家在这里找到会最好的朋友。多谢LaoshuBaby帮忙翻译! 😀

**Comment by microcai** [comment]
所以阿里的意见是跪下了？果然不配被美国制裁啊！

**Comment by microcai** [comment]
180亿罚款交的还舒服不？

**Comment by yuwei-michael** [comment]
Hi Microcai, 非常抱歉，按照我们之前群里的讨论结果，刚删除了您的不当言论，拜托请不要再发表激化矛盾的言论了，我们开源的主要目的是技术交流，欢迎您为社区多做贡献，多些技术上的指导和建议。

**Comment by microcai** [comment]
我们开会的时候，第一件事儿就是四下看看，有没有老外，没有的话，当然说汉语啦。 糟糕的莫过于就在我们觉得可以不用说英语的时候，进来个老外，或者发现角落里坐着个老外。 还有更糟糕的，角落里有个老外，我们说了几个小时英语，才发现他是来维修会议室设备的，根本不是来参加会议的。
