### ISSUE TITLE
failover datanode not work

### ISSUE THREAD

**Issue by qiuyi21** [polardb/PolarDB-for-PostgreSQL#104]
polardb_paxos.conf

`pgxcInstallDir=$HOME/polardb/polardbhome
pgxcOwner=$USER
pgxcUser=$pgxcOwner
tmpDir=/tmp
localTmpDir=$tmpDir

configBackup=n
configBackupHost=pgxc-linker
configBackupDir=$HOME/pgxc
configBackupFile=pgxc_ctl.bak
standAlone=y

dataDirRoot=$HOME/polardb/data

datanodeMasterDir=$dataDirRoot/dn_master
datanodeSlaveDir=$dataDirRoot/dn_slave
datanodeLearnerDir=$dataDirRoot/dn_learner
datanodeArchLogDir=$dataDirRoot/datanode_archlog

primaryDatanode=datanode_1
datanodeNames=(datanode_1)
datanodePorts=(10001)
datanodePoolerPorts=(10011)
datanodePgHbaEntries=(::1/128)

datanodeMasterServers=(localhost)
datanodeMasterDirs=($datanodeMasterDir)
datanodeMaxWalSender=5
datanodeMaxWALSenders=($datanodeMaxWalSender)

datanodeSlave=y

datanodeSlaveServers=(172.17.0.3)
datanodeSlavePorts=(10001)
datanodeSlavePoolerPorts=(10011)
datanodeSlaveSync=y
datanodeSlaveDirs=($datanodeSlaveDir)
datanodeArchLogDirs=( $datanodeArchLogDir)
datanodeRepNum=2
datanodeSlaveType=(3)

datanodeLearnerServers=(172.17.0.4)
datanodeLearnerPorts=(10001)
datanodeLearnerSync=y
datanodeLearnerDirs=($datanodeLearnerDir)

datanodeExtraConfig=datanodeExtraConfig
cat > $datanodeExtraConfig <<EOF
log_destination = 'stderr'
logging_collector = on
log_directory = 'pg_log'
listen_addresses = '*'
max_connections = 100
hot_standby = on
synchronous_commit = on
max_parallel_replay_workers = 0
max_worker_processes = 30
shared_preload_libraries = 'pg_cron'
cron.database_name = 'postgres'
EOF
datanodeSpecificExtraConfig=(none)
datanodeSpecificExtraPgHba=(none)`

execute pgxc_ctl -c $HOME/polardb/polardb_paxos.conf failover datanode datanode_1

`Installing pgxc_ctl_bash script as /home/postgres/pgxc_ctl/pgxc_ctl_bash.
Installing pgxc_ctl_bash script as /home/postgres/pgxc_ctl/pgxc_ctl_bash.
Reading configuration using /home/postgres/pgxc_ctl/pgxc_ctl_bash --home /home/postgres/pgxc_ctl --configuration /home/postgres/polardb/polardb_paxos.conf
Finished reading configuration.
   ******** PGXC_CTL START ***************

Current directory: /home/postgres/pgxc_ctl
Failover specified datanodes.
Failover the datanode datanode_1.
Actual Command: ssh postgres@172.17.0.3 "( pg_ctl promote  -D /home/postgres/polardb/data/dn_slave ) > /tmp/b46cca8fa206_STDOUT_17721_0 2>&1" < /dev/null > /dev/null 2>&1
Bring remote stdout: scp postgres@172.17.0.3:/tmp/b46cca8fa206_STDOUT_17721_0 /tmp/STDOUT_17721_1 > /dev/null 2>&1
waiting for server to promote............................................................... stopped waiting
pg_ctl: server did not promote in time
Actual Command: ssh postgres@localhost "( mv /home/postgres/polardb/data/dn_master/recovery.done /home/postgres/polardb/data/dn_master/recovery.conf ) > /tmp/b46cca8fa206_STDOUT_17721_2 2>&1" < /dev/null > /dev/null 2>&1
Bring remote stdout: scp postgres@localhost:/tmp/b46cca8fa206_STDOUT_17721_2 /tmp/STDOUT_17721_3 > /dev/null 2>&1
mv: cannot stat '/home/postgres/polardb/data/dn_master/recovery.done': No such file or directory
Actual Command: ssh postgres@172.17.0.3 "( pg_ctl stop -w  -D /home/postgres/polardb/data/dn_slave ; sleep 1 ) > /tmp/b46cca8fa206_STDOUT_17721_4 2>&1" < /dev/null > /dev/null 2>&1
Bring remote stdout: scp postgres@172.17.0.3:/tmp/b46cca8fa206_STDOUT_17721_4 /tmp/STDOUT_17721_5 > /dev/null 2>&1
waiting for server to shut down.... done
server stopped
Actual Command: ssh postgres@172.17.0.3 "( pg_ctl start -w  -D /home/postgres/polardb/data/dn_slave ; sleep 5 ) > /tmp/b46cca8fa206_STDOUT_17721_6 2>&1" < /dev/null > /dev/null 2>&1
Bring remote stdout: scp postgres@172.17.0.3:/tmp/b46cca8fa206_STDOUT_17721_6 /tmp/STDOUT_17721_7 > /dev/null 2>&1
waiting for server to start....2021-06-23 14:47:06.920 CST [3081] LOG:  Finished Loading Config File
2021-06-23 14:47:06.960 CST [3081] LOG:  listening on IPv4 address "0.0.0.0", port 10001
2021-06-23 14:47:06.961 CST [3081] LOG:  listening on IPv6 address "::", port 10001
2021-06-23 14:47:06.965 CST [3081] LOG:  listening on Unix socket "/tmp/.s.PGSQL.10001"
2021-06-23 14:47:06.967 CST [3081] LOG:  parallel recovery: max_queue_size 12 mb replay_buffer_size 512 kb
2021-06-23 14:47:06.971 CST [3081] LOG:  parallel recovery: max_queue_size 12 mb replay_buffer_size 512 kb
2021-06-23 14:47:06.971 CST [3081] LOG:  init parallel recovery
2021-06-23 14:47:06.971 CST [3081] LOG:  parallel recovery init: max_queue_size 12582912 replay_buffer_size 524288
2021-06-23 14:47:06.981 CST [3081] LOG:  redirecting log output to logging collector process
2021-06-23 14:47:06.981 CST [3081] HINT:  Future log output will appear in directory "pg_log".
 done
server started
psql: FATAL:  the database system is starting up
Done.`

**Comment by qiuyi21** [comment]
Installing pgxc_ctl_bash script as /home/postgres/pgxc_ctl/pgxc_ctl_bash.
Installing pgxc_ctl_bash script as /home/postgres/pgxc_ctl/pgxc_ctl_bash.
Reading configuration using /home/postgres/pgxc_ctl/pgxc_ctl_bash --home /home/postgres/pgxc_ctl --configuration /home/postgres/polardb/polardb_paxos.conf
Finished reading configuration.
   ******** PGXC_CTL START ***************

Current directory: /home/postgres/pgxc_ctl
Failover specified datanodes.
Failover the datanode datanode_1.
Actual Command: ssh postgres@localhost "( pg_ctl promote  -D /home/postgres/polardb/data/dn_slave ) > /tmp/eedd0e0738ed_STDOUT_32500_0 2>&1" < /dev/null > /dev/null 2>&1
Bring remote stdout: scp postgres@localhost:/tmp/eedd0e0738ed_STDOUT_32500_0 /tmp/STDOUT_32500_1 > /dev/null 2>&1
waiting for server to promote............................................................... stopped waiting
pg_ctl: server did not promote in time
Actual Command: ssh postgres@localhost "( mv /home/postgres/polardb/data/dn_master/recovery.done /home/postgres/polardb/data/dn_master/recovery.conf ) > /tmp/eedd0e0738ed_STDOUT_32500_2 2>&1" < /dev/null > /dev/null 2>&1
Bring remote stdout: scp postgres@localhost:/tmp/eedd0e0738ed_STDOUT_32500_2 /tmp/STDOUT_32500_3 > /dev/null 2>&1
mv: cannot stat ‘/home/postgres/polardb/data/dn_master/recovery.done’: No such file or directory
Actual Command: ssh postgres@localhost "( pg_ctl stop -w  -D /home/postgres/polardb/data/dn_slave ; sleep 1 ) > /tmp/eedd0e0738ed_STDOUT_32500_4 2>&1" < /dev/null > /dev/null 2>&1
Bring remote stdout: scp postgres@localhost:/tmp/eedd0e0738ed_STDOUT_32500_4 /tmp/STDOUT_32500_5 > /dev/null 2>&1
waiting for server to shut down.... done
server stopped
Actual Command: ssh postgres@localhost "( pg_ctl start -w  -D /home/postgres/polardb/data/dn_slave ; sleep 5 ) > /tmp/eedd0e0738ed_STDOUT_32500_6 2>&1" < /dev/null > /dev/null 2>&1
Bring remote stdout: scp postgres@localhost:/tmp/eedd0e0738ed_STDOUT_32500_6 /tmp/STDOUT_32500_7 > /dev/null 2>&1
waiting for server to start....2021-06-23 08:55:07.769 UTC [32654] LOG:  Finished Loading Config File
2021-06-23 08:55:07.774 UTC [32654] LOG:  listening on IPv4 address "0.0.0.0", port 10101
2021-06-23 08:55:07.774 UTC [32654] LOG:  listening on IPv6 address "::", port 10101
2021-06-23 08:55:07.778 UTC [32654] LOG:  listening on Unix socket "/tmp/.s.PGSQL.10101"
2021-06-23 08:55:07.780 UTC [32654] LOG:  parallel recovery: max_queue_size 12 mb replay_buffer_size 512 kb
2021-06-23 08:55:07.784 UTC [32654] LOG:  parallel recovery: max_queue_size 12 mb replay_buffer_size 512 kb
2021-06-23 08:55:07.784 UTC [32654] LOG:  init parallel recovery
2021-06-23 08:55:07.784 UTC [32654] LOG:  parallel recovery init: max_queue_size 12582912 replay_buffer_size 524288
2021-06-23 08:55:07.794 UTC [32654] LOG:  redirecting log output to logging collector process
2021-06-23 08:55:07.794 UTC [32654] HINT:  Future log output will appear in directory "pg_log".
 done
server started
ERROR:  cannot execute CREATE EXTENSION in a read-only transaction
ERROR:  cannot execute CREATE EXTENSION in a read-only transaction
ERROR:  cannot execute CREATE PROCEDURE in a read-only transaction
Done.

**Comment by yuwei-michael** [comment]
Hi qiuyi21, this is a bug , already fix now.  In Paxos HA, you can call "alter system dma change leader to '$HOST:$PGPORT'; " in leader node to do switchover,  or call "alter system dma FORCE CHANGE LEADER; " in slave node to raise leader vote. Failover will be automatic by Paxos protocol. In streaming HA, you can use pgxc_ctl failover command, if you use pgxc_ctl failover in paxos, it will give hint like "ailover command only support streaming HA, dont support paxos for now".
