### ISSUE TITLE
jdbc驱动连接问题

### ISSUE THREAD

**Issue by pangpang20** [polardb/PolarDB-for-PostgreSQL#115]
本地连接服务器端，通过dbvis，使用官方的jdbc驱动包（postgresql-42.2.23.jar），提示数据库不存在
![EE0FB608-791D-4388-BA29-6EDC7AFCF943](https://user-images.githubusercontent.com/8244232/125885935-0aa151e8-e7b1-4625-981b-197a2506aec5.png)

**Comment by mrdrivingduck** [comment]
Since newer version of PolarDB is released, this issue will be closed. If you have the same question on current stable code of PolarDB, please open a new issue. Thanks~
