### ISSUE TITLE
Can you add more detail to 'benchmark.md'? 能丰富一下benchmark.md的内容吗？

### ISSUE THREAD

**Issue by Essoz** [polardb/PolarDB-for-PostgreSQL#116]
Hi there,
I am a student doing research on distributed systems.
And I am trying to **inject some fail-slowness** into your system and investigate the performance variance.

Can you add more details to `benchmark.md`? 

I want to know your **VM size** that generates the **1600+ tps result** and your **PolarDB cluster and PG configurations**, so that I can replicate that result. 

Besides, can you **run the test without "--unlogged-table"**? I want to know how much performance is influenced by the consensus algorithm. 

It will be the best if you can deploy the system in three different machines and test it such that the network latency is considered.

**Comment by august-zp** [comment]
Hi Essoz,
`benchmark.md` is just providing a way that how to benchmark our service using other tools like `pgbench`. Different result you will get by running benchmark on different cluster or configure.

If you want to do more research, you could set up your own environment following the doc [deployment.md](https://github.com/alibaba/PolarDB-for-PostgreSQL/blob/master/doc/polardb/deployment.md) or simply deploy it using docker. Hope everything goes well with your experiment. Feel free to ask us if you fall into some trouble doing deployment.
