### ISSUE TITLE
can support help install for k8s

### ISSUE THREAD

**Issue by shikanon** [polardb/PolarDB-for-PostgreSQL#12]
if can support helm to install k8s, we can fast experience PolarDB

**Comment by yuwei-michael** [comment]
Hi shikanon, Thank you for suggestion, we will support docker or k8s operator later.
For user convenience, we have develp onekey.sh tools. You can just call "./onekey.sh all", One Key for build、configure、deploy and init paxos envirionment, after call 3 nodes paxos HA will setup in your environment by default configure. if you want deploy 3 nodes in differnt machine or build streaming HA, you can edit default configure file($HOME/polardb/polardb_paxos.conf), and call pgxc_ctl command to setup environment by your configure.

Before call "./onekey.sh all".  please setup environment variables first:
export PATH="$HOME/polardb/polarxhome/bin:$PATH"
export LD_LIBRARY_PATH="$HOME/polardb/polarxhome/lib:$LD_LIBRARY_PATH"

**Comment by mrdrivingduck** [comment]
Since newer version of PolarDB is released, this issue will be closed. If you have the same question on current stable code of PolarDB, please open a new issue. Thanks~
