### ISSUE TITLE
miss define for 'easy_spin_t' in easy_pool_t

### ISSUE THREAD

**Issue by tozhu** [polardb/PolarDB-for-PostgreSQL#120]
when compile PolarDB, hit error as following,

tracking the define, can't find 'easy_spin_t' in easy_pool_t, the structure is in file easy_pool.h

/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/util/easy_pool.c: In function 'easy_pool_create':
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/util/easy_pool.c:41:14: error: incompatible types when assigning to type 'pthread_spinlock_t' {aka 'struct _pthread_mutex'} from type 'int'
     p->tlock = EASY_SPIN_INITER;
              ^
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/util/easy_inet.c: In function 'easy_inet_parse_host':
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/util/easy_inet.c:154:17: error: too many arguments to function 'gethostbyname_r'
             if (gethostbyname_r(host, &h, buffer, 1024, &hp, &rc) || hp == NULL)
                 ^~~~~~~~~~~~~~~
In file included from /home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/util/easy_inet.c:21:
/usr/include/netdb.h:238:17: note: declared here
 struct hostent *gethostbyname_r
                 ^~~~~~~~~~~~~~~
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/util/easy_inet.c: In function 'easy_inet_hostaddr':
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/util/easy_inet.c:182:29: error: storage size of 'ifc' isn't known
     struct ifconf           ifc;
                             ^~~
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/util/easy_inet.c:190:26: error: invalid application of 'sizeof' to incomplete type 'struct ifreq'
     ifc.ifc_len = sizeof(struct ifreq) * easy_max(size, 16);
                          ^~~~~~
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/util/easy_inet.c:193:19: error: 'SIOCGIFCONF' undeclared (first use in this function)
     if (ioctl(fd, SIOCGIFCONF, (char *)&ifc) < 0)
                   ^~~~~~~~~~~
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/util/easy_inet.c:193:19: note: each undeclared identifier is reported only once for each function it appears in
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/util/easy_inet.c:198:46: error: invalid application of 'sizeof' to incomplete type 'struct ifreq'
     for (n = 0; n < ifc.ifc_len; n += sizeof(struct ifreq)) {
                                              ^~~~~~
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/util/easy_inet.c:199:33: error: dereferencing pointer to incomplete type 'struct ifreq'
         if (local || strncmp(ifr->ifr_name, "lo", 2)) {
                                 ^~
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/util/easy_inet.c:203:12: error: increment of pointer to an incomplete type 'struct ifreq'
         ifr++;
            ^~
make[6]: *** [CMakeFiles/myeasy.dir/build.make:89: CMakeFiles/myeasy.dir/util/easy_pool.c.o] Error 1
make[6]: *** Waiting for unfinished jobs....
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/ev.c: In function 'evpipe_init':
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/ev.c:1304:58: error: 'O_NOATIME' undeclared (first use in this function); did you mean 'O_NOCTTY'?
                 fcntl (evpipe [0], F_SETFL, O_NONBLOCK | O_NOATIME);
                                                          ^~~~~~~~~
                                                          O_NOCTTY
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/ev.c:1304:58: note: each undeclared identifier is reported only once for each function it appears in
make[6]: *** [CMakeFiles/myeasy.dir/build.make:128: CMakeFiles/myeasy.dir/util/easy_inet.c.o] Error 1
make[6]: *** [CMakeFiles/myeasy.dir/build.make:310: CMakeFiles/myeasy.dir/io/ev.c.o] Error 1
In file included from /home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/util/easy_pool.h:24,
                 from /home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_io_struct.h:35,
                 from /home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_io.h:23,
                 from /home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_io.c:16:
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/include/easy_atomic.h:195:26: error: invalid initializer
 #define EASY_SPIN_INITER (1)
                          ^
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_io.c:30:45: note: in expansion of macro 'EASY_SPIN_INITER'
 easy_spin_t             easy_io_list_lock = EASY_SPIN_INITER;
                                             ^~~~~~~~~~~~~~~~
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_io.c: In function 'easy_eio_create':
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_io.c:70:15: error: incompatible types when assigning to type 'pthread_spinlock_t' {aka 'struct _pthread_mutex'} from type 'int'
     eio->lock = EASY_SPIN_INITER;
               ^
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_connection.c: In function 'easy_add_listen_addr':
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_connection.c:127:20: error: incompatible types when assigning to type 'pthread_spinlock_t' {aka 'struct _pthread_mutex'} from type 'int'
     l->listen_lock = EASY_SPIN_INITER;
                    ^
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_io.c: In function 'easy_io_on_thread_start':
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_io.c:362:9: error: unknown type name 'cpu_set_t'; did you mean 'fpregset_t'?
         cpu_set_t               mask;
         ^~~~~~~~~
         fpregset_t
In file included from /home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/util/easy_pool.h:24,
                 from /home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/util/easy_string.h:24,
                 from /home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_connection.c:16:
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_connection.c: In function 'easy_switch_listen':
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/include/easy_atomic.h:148:65: error: incompatible types when assigning to type 'pthread_spinlock_t' {aka 'struct _pthread_mutex'} from type 'int'
 #define easy_unlock(lock)   {__asm__ ("" ::: "memory"); *(lock) = 0;}
                                                                 ^
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_connection.c:657:9: note: in expansion of macro 'easy_unlock'
         easy_unlock(&listen->listen_lock);
         ^~~~~~~~~~~
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_socket.c: In function 'easy_socket_listen':
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_socket.c:35:46: error: 'SOCK_DGRAM' undeclared (first use in this function); did you mean 'SEEK_DATA'?
     if ((fd = socket(address->family, (udp ? SOCK_DGRAM : SOCK_STREAM), 0)) < 0) {
                                              ^~~~~~~~~~
                                              SEEK_DATA
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_socket.c:35:46: note: each undeclared identifier is reported only once for each function it appears in
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_summary.c: In function 'easy_summary_create':
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_summary.c:55:15: error: incompatible types when assigning to type 'pthread_spinlock_t' {aka 'struct _pthread_mutex'} from type 'int'
     sum->lock = EASY_SPIN_INITER;
               ^
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_log.c: In function 'easy_log_format_default':
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_log.c:102:57: error: '__NR_gettid' undeclared (first use in this function); did you mean 'SYS_getuid'?
  lnprintf(tid_str, 64, "%d(%d)", getpid(), (int)syscall(__NR_gettid));
                                                         ^~~~~~~~~~~
                                                         SYS_getuid
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_log.c:102:57: note: each undeclared identifier is reported only once for each function it appears in
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_socket.c:35:59: error: 'SOCK_STREAM' undeclared (first use in this function); did you mean 'SMIME_STREAM'?
     if ((fd = socket(address->family, (udp ? SOCK_DGRAM : SOCK_STREAM), 0)) < 0) {
                                                           ^~~~~~~~~~~
                                                           SMIME_STREAM
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_connection.c: In function 'easy_connection_do_response':
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_connection.c:957:51: error: 'TCP_QUICKACK' undeclared (first use in this function); did you mean 'TCP_CORK'?
                     easy_socket_set_tcpopt(c->fd, TCP_QUICKACK, 1);
                                                   ^~~~~~~~~~~~
                                                   TCP_CORK
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_connection.c:957:51: note: each undeclared identifier is reported only once for each function it appears in
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_baseth_pool.c: In function 'easy_baseth_init':
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_baseth_pool.c:69:21: error: incompatible types when assigning to type 'pthread_spinlock_t' {aka 'struct _pthread_mutex'} from type 'int'
     th->thread_lock = EASY_SPIN_INITER;
                     ^
In file included from /home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/util/easy_pool.h:24,
                 from /home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_io_struct.h:35,
                 from /home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_io.h:23,
                 from /home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_io.c:16:
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_io.c: In function 'easy_signal_handler':
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/include/easy_atomic.h:148:65: error: incompatible types when assigning to type 'pthread_spinlock_t' {aka 'struct _pthread_mutex'} from type 'int'
 #define easy_unlock(lock)   {__asm__ ("" ::: "memory"); *(lock) = 0;}
                                                                 ^
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_io.c:518:5: note: in expansion of macro 'easy_unlock'
     easy_unlock(&easy_io_list_lock);
     ^~~~~~~~~~~
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_connection.c: In function 'easy_connection_do_request':
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_connection.c:1077:51: error: 'TCP_QUICKACK' undeclared (first use in this function); did you mean 'TCP_CORK'?
                     easy_socket_set_tcpopt(c->fd, TCP_QUICKACK, 1);
                                                   ^~~~~~~~~~~~
                                                   TCP_CORK
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_connection.c: In function 'easy_connection_write_again':
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_connection.c:1369:33: error: 'SHUT_WR' undeclared (first use in this function); did you mean 'SHRT_MAX'?
                 shutdown(c->fd, SHUT_WR);
                                 ^~~~~~~
                                 SHRT_MAX
make[6]: *** [CMakeFiles/myeasy.dir/build.make:284: CMakeFiles/myeasy.dir/io/easy_log.c.o] Error 1
make[6]: *** [CMakeFiles/myeasy.dir/build.make:232: CMakeFiles/myeasy.dir/io/easy_summary.c.o] Error 1
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_socket.c:44:40: error: 'TCP_DEFER_ACCEPT' undeclared (first use in this function); did you mean 'SYS_F_ACCEPT'?
             easy_socket_set_tcpopt(fd, TCP_DEFER_ACCEPT, 1);
                                        ^~~~~~~~~~~~~~~~
                                        SYS_F_ACCEPT
make[6]: *** [CMakeFiles/myeasy.dir/build.make:219: CMakeFiles/myeasy.dir/io/easy_baseth_pool.c.o] Error 1
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_connection.c: In function 'easy_connection_do_connect':
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_connection.c:1624:48: error: 'SOCK_STREAM' undeclared (first use in this function); did you mean 'SMIME_STREAM'?
     if (fd < 0 && (fd = socket(addr.ss_family, SOCK_STREAM, 0)) < 0) {
                                                ^~~~~~~~~~~
                                                SMIME_STREAM
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_socket.c:45:40: error: 'TCP_SYNCNT' undeclared (first use in this function); did you mean 'TCP_KEEPCNT'?
             easy_socket_set_tcpopt(fd, TCP_SYNCNT, 2);
                                        ^~~~~~~~~~
                                        TCP_KEEPCNT
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_socket.c:59:36: error: 'AF_INET' undeclared (first use in this function)
             if (address->family == AF_INET && (*flags & EASY_FLAGS_NOLISTEN)) {
                                    ^~~~~~~
make[6]: *** [CMakeFiles/myeasy.dir/build.make:167: CMakeFiles/myeasy.dir/io/easy_io.c.o] Error 1
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_connection.c: In function 'easy_connection_autoconn':
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_connection.c:1857:38: error: 'SOCK_STREAM' undeclared (first use in this function); did you mean 'SMIME_STREAM'?
     if ((fd = socket(addr.ss_family, SOCK_STREAM, 0)) < 0) {
                                      ^~~~~~~~~~~
                                      SMIME_STREAM
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_socket.c:66:33: error: 'SO_REUSEADDR' undeclared (first use in this function); did you mean 'IP_REUSEADDR'?
     if (easy_socket_set_opt(fd, SO_REUSEADDR, 1) < 0) {
                                 ^~~~~~~~~~~~
                                 IP_REUSEADDR
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_socket.c:71:28: error: 'AF_INET6' undeclared (first use in this function); did you mean 'BE_IN16'?
     if (address->family == AF_INET6) {
                            ^~~~~~~~
                            BE_IN16
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_connection.c: In function 'easy_connection_destroy_dispatch':
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_connection.c:2239:21: error: 'SHUT_RD' undeclared (first use in this function)
     shutdown(c->fd, SHUT_RD);
                     ^~~~~~~
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_connection.c: In function 'easy_connection_checkself':
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_socket.c: In function 'easy_socket_non_blocking':
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_socket.c:266:22: error: 'FIONBIO' undeclared (first use in this function); did you mean 'UIO_XUIO'?
     return ioctl(fd, FIONBIO, &flags);
                      ^~~~~~~
                      UIO_XUIO
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_connection.c:2249:27: error: 'AF_INET' undeclared (first use in this function)
     if (c->addr.family == AF_INET && getsockname(c->fd, (struct sockaddr *)&addr, &len) == 0) {
                           ^~~~~~~
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_socket.c: In function 'easy_socket_set_opt':
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_socket.c:278:27: error: 'SOL_SOCKET' undeclared (first use in this function); did you mean 'SYS_F_SOCKET'?
     return setsockopt(fd, SOL_SOCKET, option, (void *)&value, sizeof(value));
                           ^~~~~~~~~~
                           SYS_F_SOCKET
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_socket.c: In function 'easy_socket_support_ipv6':
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_socket.c:284:41: error: 'AF_INET6' undeclared (first use in this function); did you mean 'BE_IN16'?
     int                     fd = socket(AF_INET6, SOCK_STREAM, 0);
                                         ^~~~~~~~
                                         BE_IN16
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_socket.c:284:51: error: 'SOCK_STREAM' undeclared (first use in this function); did you mean 'SMIME_STREAM'?
     int                     fd = socket(AF_INET6, SOCK_STREAM, 0);
                                                   ^~~~~~~~~~~
                                                   SMIME_STREAM
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_socket.c: In function 'easy_socket_udpwrite':
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_socket.c:305:29: error: storage size of 'msg' isn't known
     struct msghdr           msg;
                             ^~~
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_socket.c: In function 'easy_socket_error':
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_socket.c:343:24: error: 'SOL_SOCKET' undeclared (first use in this function); did you mean 'SYS_F_SOCKET'?
     if (getsockopt(fd, SOL_SOCKET, SO_ERROR, (void *) &err, &len) == -1)
                        ^~~~~~~~~~
                        SYS_F_SOCKET
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_socket.c:343:36: error: 'SO_ERROR' undeclared (first use in this function); did you mean 'EV_ERROR'?
     if (getsockopt(fd, SOL_SOCKET, SO_ERROR, (void *) &err, &len) == -1)
                                    ^~~~~~~~
                                    EV_ERROR
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_socket.c: In function 'easy_socket_set_linger':
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_socket.c:351:19: error: storage size of 'so_linger' isn't known
     struct linger so_linger;
                   ^~~~~~~~~
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_socket.c:354:27: error: 'SOL_SOCKET' undeclared (first use in this function); did you mean 'SYS_F_SOCKET'?
     return setsockopt(fd, SOL_SOCKET, SO_LINGER, &so_linger, sizeof(so_linger));
                           ^~~~~~~~~~
                           SYS_F_SOCKET
/home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/io/easy_socket.c:354:39: error: 'SO_LINGER' undeclared (first use in this function); did you mean 'SI_TIMER'?
     return setsockopt(fd, SOL_SOCKET, SO_LINGER, &so_linger, sizeof(so_linger));
                                       ^~~~~~~~~
                                       SI_TIMER
make[6]: *** [CMakeFiles/myeasy.dir/build.make:297: CMakeFiles/myeasy.dir/io/easy_connection.c.o] Error 1
make[6]: *** [CMakeFiles/myeasy.dir/build.make:193: CMakeFiles/myeasy.dir/io/easy_socket.c.o] Error 1
make[5]: *** [CMakeFiles/Makefile2:73: CMakeFiles/myeasy.dir/all] Error 2
make[4]: *** [Makefile:130: all] Error 2
make[3]: *** [CMakeFiles/libmyeasy.dir/build.make:62: /home/tony/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/polar_wrapper/lib/libmyeasy.a] Error 2
make[2]: *** [CMakeFiles/Makefile2:110: CMakeFiles/libmyeasy.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:122: CMakeFiles/libmyeasy.dir/rule] Error 2
make: *** [Makefile:177: libmyeasy] Error 2

**Comment by tozhu** [comment]
OS version is Hunghu OS, a fork from illumos or Solaris, has fixed the including head for the OS

index e74d5ad..f5eebc2 100644
--- a/src/backend/polar_dma/libconsensus/dependency/easy/src/io/ev.c
+++ b/src/backend/polar_dma/libconsensus/dependency/easy/src/io/ev.c
@@ -183,7 +183,11 @@
 #include <sys/types.h>
 #include <time.h>
 #include <limits.h>
+#ifdef __linux__
 #include <syscall.h>
+#elif __solaris__
+#include <sys/syscall.h>
+#endif
 #include <signal.h>

 #ifdef EV_H
diff --git a/src/backend/polar_dma/libconsensus/dependency/easy/src/util/easy_inet.c b/src/backend/polar_dma/libconsensus/dependency/easy/src/util/easy_inet.c
index f6b9ca6..3841d4e 100644
--- a/src/backend/polar_dma/libconsensus/dependency/easy/src/util/easy_inet.c
+++ b/src/backend/polar_dma/libconsensus/dependency/easy/src/util/easy_inet.c
@@ -21,7 +21,11 @@
 #include <netdb.h>
 #include <arpa/inet.h>      // inet_addr
 #include <sys/ioctl.h>
+#ifdef __linux__
 #include <linux/if.h>
+#elif __solaris__
+#include <net/if.h>
+#endif

**Comment by mengborong** [comment]
On Hunghu OS, pthread_spinlock_t may be not type int. So, it can not assign EASY_SPIN_INITER to pthread_spinlock_t. you can adapt easy_spin_lock to Hunghu OS, and compile libeasy without define EASY_SPIN_USE_SYS.
