### ISSUE TITLE
默认ssh 端口非22 的时候，如何配置 ？

### ISSUE THREAD

**Issue by yiwanbaimifan** [polardb/PolarDB-for-PostgreSQL#124]
配置自定义部署 - 多主机流复制环境部署的示例时候，测试服务器ssh非22端口的时候， 
执行：
pgxc_ctl -c $HOME/polardb/polardb_streaming.conf init all

后提示

ssh: connect to host xxx.xx.xx.xxx port 22: Connection timed out

请问这个ssh 端口在哪里配置

**Comment by yuwei-michael** [comment]
目前程序中没有针对修改ssh端口的配置，建议将ssh端口修改回默认22。

**Comment by yiwanbaimifan** [comment]
@yuwei-michael 好的了解了 谢谢
