### ISSUE TITLE
Dockerfile in distributed branch, git clone miss -b distributed 

### ISSUE THREAD

**Issue by luyaning** [polardb/PolarDB-for-PostgreSQL#144]
File docker/Dockerfile, line 66:
	&& git clone https://github.com/alibaba/PolarDB-for-PostgreSQL.git \
should be:
	&& git clone -b distributed https://github.com/alibaba/PolarDB-for-PostgreSQL.git \
to get distributed version of PolarDB-for-PostgreSQL.
First hand error mesage is "onekey.sh  not found"

**Comment by fengzunbao** [comment]
fixed
16bf61b8674981a53e361268e065efa1c3646872
