### ISSUE TITLE
The souce code of paxos seems not open ? 

### ISSUE THREAD

**Issue by triump2020** [polardb/PolarDB-for-PostgreSQL#15]

**Comment by yuwei-michael** [comment]
Hi triump2020, Yes, you are right. Paxos library still not open source, we reference it's dynamic library when build paxos HA for now. we will open source it later since it's need more process work.

**Comment by triump2020** [comment]
That's great !

**Comment by yuwei-michael** [comment]
> That's great !

Paxos library already open source , please check commit "3b2a3a8cea2a872c0179e8d0ebe50a482420bb0a"
