### ISSUE TITLE
 ERROR:  could not access status of transaction

### ISSUE THREAD

**Issue by phamduykhuong** [polardb/PolarDB-for-PostgreSQL#167]
Run pgbench all node (primary: read+write, replica: read only), a few seconds later, all transactions on  all replica nodes aborted. Check output log on replicas look like:

ERROR:  could not access status of transaction 400328315
DETAIL:  Could not read from file "file-dio:///share/data_dir_polardb_pg/pg_xact/017D" at offset 204800: Success.
STATEMENT:  SELECT abalance FROM pgbench_accounts WHERE aid = 43382117;
ERROR:  could not access status of transaction 400336937
DETAIL:  Could not read from file "file-dio:///share/data_dir_polardb_pg/pg_xact/017D" at offset 204800: Success.
STATEMENT:  SELECT abalance FROM pgbench_accounts WHERE aid = 48712442;
LOG:  could not send data to client: Broken pipe
FATAL:  connection to client lost
ERROR:  could not access status of transaction 400327570
DETAIL:  Could not read from file "file-dio:///share/data_dir_polardb_pg/pg_xact/017D" at offset 204800: Success.
STATEMENT:  SELECT abalance FROM pgbench_accounts WHERE aid = 50179077;
ERROR:  could not access status of transaction 400348751
STATEMENT:  SELECT abalance FROM pgbench_accounts WHERE aid = 46276451;
ERROR:  could not access status of transaction 400336229
DETAIL:  Could not read from file "file-dio:///share/data_dir_polardb_pg/pg_xact/017D" at offset 204800: Success.
STATEMENT:  SELECT abalance FROM pgbench_accounts WHERE aid = 47798317;
ERROR:  could not access status of transaction 400330649
DETAIL:  Could not read from file "file-dio:///share/data_dir_polardb_pg/pg_xact/017D" at offset 204800: Success.

**Comment by mrdrivingduck** [comment]
Since newer version of PolarDB is released, this issue will be closed. If you have the same question on current stable code of PolarDB, please open a new issue. Thanks~
