### ISSUE TITLE
支持ubuntu环境下运行PolarDB

### ISSUE THREAD

**Issue by fengzunbao** [polardb/PolarDB-for-PostgreSQL#177]
支持ubuntu环境下运行PolarDB，并更新Readme-CN中快速入门文档

**Comment by Jiwenguan** [comment]
您好，您的邮件我已收到，愿您身体健康，万事如意！

**Comment by mrdrivingduck** [comment]
Since PolarDB can be running in a docker container, it can run on Ubuntu, too.
