### ISSUE TITLE
请问PostgreSQL中的临时表或者本地日志文件放在本地还是PolarFS

### ISSUE THREAD

**Issue by wudidapaopao** [polardb/PolarDB-for-PostgreSQL#178]
请问PostgreSQL中的临时表或者本地日志文件放在本地还是PolarFS，浏览了下相关代码好像没有看到判断一个文件(比如临时表或者本地日志)是放在本地文件系统还是PolarFS。

**Comment by fengzunbao** [comment]
临时表和日志文件存储在本地

**Comment by Jiwenguan** [comment]
您好，您的邮件我已收到，愿您身体健康，万事如意！
