### ISSUE TITLE
初始化数据库报错

### ISSUE THREAD

**Issue by gdpnxzh** [polardb/PolarDB-for-PostgreSQL#199]
用的是ceph的rbd,
初始化时报如下错，是什么问题呢？
sudo /home/postgres/tmp_basedir_polardb_pg_1100_bld/bin/polar-initdb.sh /home/postgres/primary/ /rbd1/polardb_data/

[PFS_LOG] Mar 17 12:12:01.703790 INF [2357] pid: 2277, caller: sshd: root@pts/1      
[PFS_LOG] Mar 17 12:12:01.703876 INF [2357] pid: 996, caller: /usr/sbin/sshd -D  
[PFS_LOG] Mar 17 12:12:01.703979 ERR [2357] cp: can't find any pbdname
[PFS_LOG] Mar 17 12:12:01.704013 ERR [2357] cp failed: impl specific
cp failed: impl specific

**Comment by mrdrivingduck** [comment]
Please provide more information.
