### ISSUE TITLE
可以提供一个docker镜像吗？想快速试用一下。

### ISSUE THREAD

**Issue by hegphegp** [polardb/PolarDB-for-PostgreSQL#2]

**Comment by leisurelyclouds** [comment]
只有docker镜像很难测试高可用 集群的特性啊
所以如果提供 k8s operator 会更好
---
It's hard to test the features of a highly available cluster with only docker images
So it would be better to provide k8s operator

**Comment by raywill** [comment]
Please edit your title in English.

**Comment by leisurelyclouds** [comment]
Installing this plugin will solve this problem
https://github.com/marketplace/actions/issues-translator

**Comment by yuwei-michael** [comment]
Hi leisurelyclouds, Thank you for your suggestion, we will support docker or k8s operator soon. 
For user convenience, we have develp onekey.sh tools. You can call "./onekey.sh all", One Key for build、configure、deploy and init paxos envirionment, after call 3 nodes paxos HA will automatic setup in your environment. if you want deploy 3 nodes in differnt machine or build streaming HA, you can edit default configure file($HOME/polardb/polardb_paxos.conf), and call pgxc_ctl command to setup environment by your configure. 


Before call "./onekey.sh all". please setup environment variables first:
export PATH="$HOME/polardb/polarxhome/bin:$PATH"
export LD_LIBRARY_PATH="$HOME/polardb/polarxhome/lib:$LD_LIBRARY_PATH"
