### ISSUE TITLE
[Doc]please add the copyright year in the notice file

### ISSUE THREAD

**Issue by king-gao** [polardb/PolarDB-for-PostgreSQL#228]
** In [notice file](https://github.com/ApsaraDB/PolarDB-for-PostgreSQL/blob/POLARDB_11_STABLE/NOTICE)**
I saw the copyright start in 2020, but I found the PR continue merge in 2021 and 2022.

please follow the copyright law add the year , thank you !

**Comment by fengzunbao** [comment]
Thanks for the tip. We change the copyright  date in NOTICE file from 2020 to 2021-2022 according to the copyright law.
