### ISSUE TITLE
[ASoC] PolarDB HTAP 支持并行加速创建物化视图

### ISSUE THREAD

**Issue by lanzhao0329** [polardb/PolarDB-for-PostgreSQL#247]
### 题目描述

在 CREATE MATERIALIZED VIEW（创建物化视图）时需要按需对表中的元组进行扫描。
[PostgreSQL: Documentation: 14: 41.3. Materialized Views](https://www.postgresql.org/docs/current/rules-materializedviews.html)

### 项目目标

通过 PolarDB 的 HTAP 能力并行加速这个过程。

### 项目技术要求

熟悉C语言及Linux上的相关调试技术，对 PostgreSQL 内核有一定了解。

### 题目难度

中等 

### 导师信息
Zhang Jingtang，[@mrdrivingduck](https://github.com/mrdrivingduck) , ASoC Mentor, [PolarDB-for-PostgreSQL](https://github.com/ApsaraDB/PolarDB-for-PostgreSQL) maintainer.
zhangjingtang.zjt@alibaba-inc.com（联系导师请附上个人简历）

**Comment by mrdrivingduck** [comment]
The PR has been merge in #284, congratulations to @pyh4 for his first contribution in PolarDB!
