### ISSUE TITLE
2022 Alibaba Summer of Code

### ISSUE THREAD

**Issue by lanzhao0329** [polardb/PolarDB-for-PostgreSQL#248]
Welcome to the open source world! If you haven't planned how to spend this summer, come to the Alibaba Summer of Code and code with us! 💻
Alibaba Summer of Code is a global program focused on engaging students directly in open source software development. Under the guidance of the mentor in the Alibaba open source project, students can experience software development in the real world. Alibaba Summer of code will begin from May 30th to September 1st. Students can use the summertime to participate in the open source project and work with the core members of the project.

### What you can get?

On this exclusive developer journey, students will have the opportunity to:
● Participate in the top projects of the International Open Source Foundation;
● Get a scholarship from Alibaba;
● Obtain an open source contributor certificate;
● Get a fast pass of Alibaba Internship
● Get your code adopted and used by the open source project！

### Our Mentor

He kewen，[@HBKO](https://github.com/HBKO) ，ASoC Mentor, [PolarDB-for-PostgreSQL](https://github.com/ApsaraDB/PolarDB-for-PostgreSQL) Committer.
Zhang Jingtang，[@mrdrivingduck](https://github.com/mrdrivingduck) ，ASoC Mentor, [PolarDB-for-PostgreSQL](https://github.com/ApsaraDB/PolarDB-for-PostgreSQL) Committer.
Sun Mengshi，ASoC Mentor,  [PolarDB-X](https://github.com/ApsaraDB/galaxysql) Committer.
Wu Di，[@vettalwu](https://github.com/vettalwu)，ASoC Mentor, [PolarDB-X](https://github.com/ApsaraDB/galaxysql) Committer.

### Timeline

![image](https://user-images.githubusercontent.com/106291261/170412073-2b9a75ea-6c6d-4251-8557-61e66f103f37.png)

### Apply Now!

1. Browse open idea list here:
[[ASoC] PolarDB HTAP 支持 COPY 导入数据的分布式加速](https://github.com/ApsaraDB/PolarDB-for-PostgreSQL/issues/246)
[[ASoC] PolarDB HTAP 支持并行加速创建物化视图](https://github.com/ApsaraDB/PolarDB-for-PostgreSQL/issues/247)
[[ASoC] PolarDB-X Operator 混沌测试实践](https://github.com/ApsaraDB/galaxysql/issues/56)
[[ASoC] PolarDB-X 支持 DBLink](https://github.com/ApsaraDB/galaxysql/issues/57)

3. Upload your CV and project proposal via ASOC 2022 official website
https://opensource.alibaba.com/asoc2022
Contact the Organizer
If you have any questions, visit the event website:https://opensource.alibaba.com/asoc2022
Email address:  
Email address: opensource@alibaba-inc.com

PolarDB-PG 开源交流钉钉群：
![image](https://user-images.githubusercontent.com/106291261/170616822-c73d2d13-9e7a-4812-b589-376896cf5822.png)

PolarDB-X 开源交流钉钉群
![image](https://user-images.githubusercontent.com/106291261/170427621-7d8d3e7d-9f7d-449d-945a-7cf23c51b79e.png)

**Comment by zzk0** [comment]
"PolarDB-PG 开源交流钉钉群" 二维码已经失效了，请重新分享一下呗😀

**Comment by lanzhao0329** [comment]
> 

已经更新，请重新扫码进入哈

**Comment by lanzhao0329** [comment]
> "PolarDB-PG 开源交流钉钉群" 二维码已经失效了，请重新分享一下呗😀

已经更新，请重新扫码进入哈

**Comment by Aikatsui** [comment]
@lanzhao0329 @mrdrivingduck asoc2022 does that only available in mainland? e.g. not available for asian countries? otherwise usually see Gsoc etc dominance

**Comment by sujithranga** [comment]
@lanzhao0329 @mrdrivingduck asoc2022 does that only available in mainland? e.g. not available for asian countries? otherwise usually see Gsoc etc dominance

**Comment by lanzhao0329** [comment]
> 
Alibaba Summer of Code is a global program focused on engaging students directly in open source software development.
Welcome to our project

**Comment by lanzhao0329** [comment]
> @lanzhao0329 @mrdrivingduck asoc2022 does that only available in mainland? e.g. not available for asian countries? otherwise usually see Gsoc etc dominance

Alibaba Summer of Code is a global program focused on engaging students directly in open source software development.
Welcome to our project
