### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by Jackarain** [polardb/PolarDB-for-PostgreSQL#25]
在拉取了最新代码，执行./build.sh进行编译，然而并不能正常编译通过，我不知道你们是怎么编译通过的。
gcc version 10.2.0
cmake version 3.19.6

细节请看：

https://asciinema.org/a/GUXq3STFScbiUDTPy4avaMODk

类似
/root/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/thread/easy_uthread.c:266:17: error: ‘SIG_BLOCK’ undeclared (first use in this function)
这种，应该是你们编码错误，定义 SIG_BLOCK 的头文件```<signal.h>```都没 include 吧

这个错误我猜应该是用到 SIG_BLOCK 的源文件中没 include，而是隐藏在其它3方库里include了，而我这里恰恰没有这个3方库。但是不得不说，这是一个不好的编码习惯。比如 
```#include <iostream>```
之后用到了std::string，不包含 ```<string> ```也是能用 std::string 的，但这不是个好习惯，不能依赖间接包含，何况你这是间接依赖了一个3方库中的 include。

出错的地方有点多，麻烦看bash录制的视频。

希望你们能弄的健壮一点，像pg那样一次编译通过，无需折腾

**Comment by mengborong** [comment]
> 在拉取了最新代码，执行./build.sh进行编译，然而并不能正常编译通过，我不知道你们是怎么编译通过的。
> gcc version 10.2.0
> cmake version 3.19.6
> 
> 细节请看：
> 
> https://asciinema.org/a/GUXq3STFScbiUDTPy4avaMODk
> 
> 类似
> /root/PolarDB-for-PostgreSQL/src/backend/polar_dma/libconsensus/dependency/easy/src/thread/easy_uthread.c:266:17: error: ‘SIG_BLOCK’ undeclared (first use in this function)
> 这种，应该是你们编码错误，定义 SIG_BLOCK 的头文件<signal.h>都没 include 吧
> 出错的地方有点多，麻烦看bash录制的视频。
> 
> 希望你们能弄的健壮一点，像pg那样一次编译通过，无需折腾

请先使用gcc 4.8或者7.2编译，consensus library后续会增加对于高版本gcc的支持，也非常欢迎大家一起参与。

**Comment by mengborong** [comment]
@Jackarain 最新代码已经支持了gcc 10的编译，请拉取下最新版本代码。

**Comment by Jackarain** [comment]
> @Jackarain 最新代码已经支持了gcc 10的编译，请拉取下最新版本代码。

不错不错！
