### ISSUE TITLE
[Bug] Compile failed missing llvm-config

### ISSUE THREAD

**Issue by fansehep** [polardb/PolarDB-for-PostgreSQL#258]
**Describe the bug**
I pull the offical container, but when i execute
```bash
./polardb_build.sh
```
here is a error
and the container does not install the gcc, and llvm, It's better add it in https://apsaradb.github.io/PolarDB-for-PostgreSQL/zh/guide/db-localfs.html#%E6%9C%AC%E5%9C%B0%E5%8D%95%E8%8A%82%E7%82%B9%E5%AE%9E%E4%BE%8B
**To Reproduce**
1. xxx
2. xxx
3. xxx

**Expected behavior**

**Screenshots**
![2022-06-14_18-06-1655201328](https://user-images.githubusercontent.com/75058860/173557653-fe6c59aa-c8c3-4c7a-b745-57a15885b173.jpg)

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7]

**Additional context**

**Comment by mrdrivingduck** [comment]
Make sure you are using the most recent [development image](https://hub.docker.com/r/polardb/polardb_pg_devel/tags) on DockerHub, and make sure you are on the stable branch `POLARDB_11_STABLE` or stable development branch `POLARDB_11_DEV` or any checkout branches.

**Comment by fansehep** [comment]
ok, thanks, he successfully compiled.
