### ISSUE TITLE
 make error on centos8

### ISSUE THREAD

**Issue by renxiangchen** [polardb/PolarDB-for-PostgreSQL#26]
![image](https://user-images.githubusercontent.com/56289742/120788692-35cd1900-c563-11eb-9b4d-ee8ef731e477.png)

**Comment by mengborong** [comment]
@renxiangchen Please pull latest code.  And reference https://github.com/alibaba/PolarDB-for-PostgreSQL#deployment-from-source-code for the detailed steps.
