### ISSUE TITLE
How does PxPolicy work?[Question]

### ISSUE THREAD

**Issue by Weijun-H** [polardb/PolarDB-for-PostgreSQL#280]
**Describe the problem**
Now I am working on the distributed version of `COPY`, but I met some troubles. 

In `struct RelationData`, this is a member 
```
/* POLAR px */
struct PxPolicy *rd_pxpolicy; /* Partitioning info if distributed rel */
/* POLAR end */
```
But I did not find where it was initialized or updated. Does this value work the same way as in Greenplum? If not, how does it work in PolarDB?
Thank you very much.

**Comment by mrdrivingduck** [comment]
> **Describe the problem** Now I am working on the distributed version of `COPY`, but I met some troubles.
> 
> In `struct RelationData`, this is a member
> 
> ```
> /* POLAR px */
> struct PxPolicy *rd_pxpolicy; /* Partitioning info if distributed rel */
> /* POLAR end */
> ```
> 
> But I did not find where it was initialized or updated. Does this value work the same way as in Greenplum? If not, how does it work in PolarDB? Thank you very much.

Seems that we are not using it.
