### ISSUE TITLE
PolarDB 可以支持多租户业务的资源隔离吗？

### ISSUE THREAD

**Issue by zhangucan** [polardb/PolarDB-for-PostgreSQL#29]

**Comment by digoal** [comment]
可以增加一些输入, 具体是什么业务场景, 遇到了哪些挑战, 希望数据库层面做什么来应对这些挑战?

**Comment by mrdrivingduck** [comment]
Since newer version of PolarDB is released, this issue will be closed. If you have the same question on current stable code of PolarDB, please open a new issue. Thanks~
