### ISSUE TITLE
[Bug] build with PFS  report an error

### ISSUE THREAD

**Issue by xu-chaojie** [polardb/PolarDB-for-PostgreSQL#290]
**Describe the bug**

<img width="793" alt="image" src="https://user-images.githubusercontent.com/5245004/183836189-e60749d7-d0ef-4cd7-82e0-71e394bb121d.png">

<img width="535" alt="image" src="https://user-images.githubusercontent.com/5245004/183836369-740551c1-8ff4-436a-9d89-e711d3ade546.png">

**To Reproduce**
1.  ./polardb_build.sh --with-pfsd

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: debian9
 - Version POLARDB_11_STABLE

**Additional context**

**Comment by mrdrivingduck** [comment]
@xu-chaojie The compilation of this part requires OpenSSL **1.1.1**, in which SM2/SM3/SM4 algorithm of China standard is supported. You can see the [release notes](https://www.openssl.org/blog/blog/2018/09/11/release111/) of OpenSSL 1.1.1, and check OpenSSL version on your Debian system.

**Comment by xu-chaojie** [comment]
ok, thanks
