### ISSUE TITLE
[Question] Are this polardb open source ready for productions ?

### ISSUE THREAD

**Issue by Jayuda** [polardb/PolarDB-for-PostgreSQL#291]
Hello guys, sorry for this stupid questions : 
Are this polardb open source ready for productions ?
If yes, i already try with branch distribution - but still confuse to use in real production.
Thanks anyway

**Comment by mrdrivingduck** [comment]
Yes, it is ready for production. It is the same version we are using on public clouds. @Jayuda

**Comment by Jayuda** [comment]
Great's, i will try on my systems. Thanks

**Comment by mrdrivingduck** [comment]
@Jayuda You can refer to our docs [here](https://apsaradb.github.io/PolarDB-for-PostgreSQL/), and free to ask questions in issues.
