### ISSUE TITLE
[Question] Is it fully compatible with Postgres, including the existing Postgres drivers for Java / PHP languages?

### ISSUE THREAD

**Issue by fishfree** [polardb/PolarDB-for-PostgreSQL#293]
如题：请问下我可以使用现存的各类开发语言的Postgres的客户端驱动来对接和Postgres语法吗？

**Comment by mrdrivingduck** [comment]
Hi @fishfree . Thanks for your interest in PolarDB for PostgreSQL.

**Comment by mrdrivingduck** [comment]
Hi @fishfree . Thanks for your interest in PolarDB for PostgreSQL.

PolarDB for PostgreSQL is 100% compatible with PostgreSQL, including protocols between client and backend server. So you are free to use PostgreSQL client drivers and grammar.
