### ISSUE TITLE
按照readme说明编译完后，没有生成pgxc_ctl二进制文件，是少了什么步骤吗

### ISSUE THREAD

**Issue by yejr** [polardb/PolarDB-for-PostgreSQL#3]

**Comment by raywill** [comment]
please edit your title in English.

**Comment by JeffDeans** [comment]
cd contrib
make && make install to generate pgxc_ctl binary file in PGXC_CTL_HOME

**Comment by pupillord** [comment]
> make && make install to generate pgxc_ctl binary file in PGXC_CTL_HOME

编译到一般停止了： make: *** 没有规则可以创建目标“to”。 停止。

**Comment by yuwei-michael** [comment]
We have develop build.sh script for build all binary include pgxc_ctl, no need enter contrib directory to build again. but the default PG_INSTALL path in build.sh is different with readme, it is unified already, please update the code and try again.

**Comment by microcai** [comment]
> please edit your title in English.

你是哪国人？

**Comment by yuwei-michael** [comment]
I am Chinese, some of our team member is from USA.

**Comment by microcai** [comment]
> I am Chinese, some of our team member is from USA.

入乡就得随俗。来中国工作，就必须学会汉语。怎么招了一个老外，就得全赔他说英语了？你们是三陪么？

**Comment by microcai** [comment]
习大大都说了。我们要平视这个世界。阿里的人怎么还要梦回大清啊

**Comment by yuwei-michael** [comment]
Hi microcai ，this community is belong all of us, you are also the owner!  you can choose English or Chinese based on your habit.

**Comment by microcai** [comment]
开放就是用英语？？？　用英语就开放了？那美国那么开放，咋就只用英语呢？能不要这么双标吗？我最讨厌这种土狗子放洋屁了，你自己打英文，没人管你，但是还要求别人也用英文，还说自己团队有美国人，就要说英语，我要笑死。

**Comment by yuwei-michael** [comment]
Hi microcai，语言只是载体，无论用中文还是英文，只要能更好的表达自己的观点就可以，以后如果有人愿意用中文讨论，就用中文回复吧。

**Comment by stevefan1999-personal** [comment]
> 开放就是用英语？？？　用英语就开放了？那美国那么开放，咋就只用英语呢？能不要这么双标吗？我最讨厌这种土狗子放洋屁了，你自己打英文，没人管你，但是还要求别人也用英文，还说自己团队有美国人，就要说英语，我要笑死。

美國人用西班牙語的比例並不少 @microcai 

https://en.wikipedia.org/wiki/Spanish_language_in_the_United_States?wprov=sfla1

RMS本身也會西班牙語

https://youtu.be/fZXFMzbNZx8

**Comment by yuwei-michael** [comment]
Thank you all of your suggestion from microcai, stevefan1999-personal. We will continue to keep those rules base on our first discuss, the Language is supporter, your opinion is more important, so you can choose your language by your habit. and the reply will follow the quizzer language.

**Comment by microcai** [comment]
> > 开放就是用英语？？？　用英语就开放了？那美国那么开放，咋就只用英语呢？能不要这么双标吗？我最讨厌这种土狗子放洋屁了，你自己打英文，没人管你，但是还要求别人也用英文，还说自己团队有美国人，就要说英语，我要笑死。
> 
> 美國人用西班牙語的比例並不少 @microcai
> 
> https://en.wikipedia.org/wiki/Spanish_language_in_the_United_States?wprov=sfla1
> 
> RMS本身也會西班牙語
> 
> https://youtu.be/fZXFMzbNZx8

这不是证明了英语人口更少了嘛。一点也不通用嘛。

**Comment by stevefan1999-personal** [comment]
> > > 开放就是用英语？？？　用英语就开放了？那美国那么开放，咋就只用英语呢？能不要这么双标吗？我最讨厌这种土狗子放洋屁了，你自己打英文，没人管你，但是还要求别人也用英文，还说自己团队有美国人，就要说英语，我要笑死。
> > 
> > 
> > 美國人用西班牙語的比例並不少 @microcai
> > https://en.wikipedia.org/wiki/Spanish_language_in_the_United_States?wprov=sfla1
> > RMS本身也會西班牙語
> > https://youtu.be/fZXFMzbNZx8
> 
> 这不是证明了英语人口更少了嘛。一点也不通用嘛。

因為現在的世界是西方文明主導 所以英語依然是強勢的 你想怎麼改變這個現況呢？

**Comment by zopyx** [comment]
@yuwei-michael 平心而论，用中文触动了哪根弦？无非就是一些人觉得英语更有B格而已，装B而已，而且觉得自己的母语低贱。
中文就不能交流吗？所有交流就一定要让老外也能看懂吗？那么老外和老外之间交流，什么时候说为了照顾华人，用中文交流？他们绝不会有半点这种想法。
至少我和中国人说话，不可能要求对面给我讲外语，因为我腿脚不利索，跪不下去。
