### ISSUE TITLE
[Question][Roadmap]超融合数据库

### ISSUE THREAD

**Issue by ChenpiDog** [polardb/PolarDB-for-PostgreSQL#306]
增强方向（一切皆SQL）：
1）实时ETL/流数据处理：仅靠SQL就能实现实时ETL/流数据处理；
2）机器学习：库内机器学习，通过类SQL实现常用机器学习（可离线可实时）；
3）时序数据库。

背景：目前大数据的组件越来越多，使用及维护变得越来越麻烦，并且会造成数据冗余在各个组件里，形成数据孤岛。超融合数据库性价比高，能大大简化技术栈，降低系统复杂度，降低运维复杂度，提升开发效率。分久必合，超融合数据库有很好的发展前景。

**Comment by ChenpiDog** [comment]
希望能公布一个项目开发规划的Roadmap。

**Comment by Fe8N** [comment]
Roadmap can refer this doc: https://github.com/ApsaraDB/PolarDB-for-PostgreSQL/blob/distributed_dev/doc/polardb/roadmap.md
