### ISSUE TITLE
[Question] upstream的 jit 内存泄漏问题 polardb-for-PG 有处理吗

### ISSUE THREAD

**Issue by ZhangHuiGui** [polardb/PolarDB-for-PostgreSQL#312]
**Describe the problem**
看到polardb-for-pg 也会使用LLVM，所以 JIT 也在用对吧？
 
开启JIT 之后，build_inline的过程会llvm的一些types有内存泄漏问题，upstream 15 版本之前其实都有这个问题。
https://www.postgresql.org/message-id/20201001021609.GC8476%40telsasoft.com

现象就是 开启JIT，在一个backend上跑大量的sql，这个backend 进程物理内存会持续上涨，polar这边
有没有处理这个问题呢？
...

**Comment by Jiwenguan** [comment]
您好，您的邮件我已收到，愿您身体健康，万事如意！

**Comment by mrdrivingduck** [comment]
Hi @ZhangHuiGui :

PolarDB for PostgreSQL **does** use JIT, but does not modify the code of this part. As the issue you have mentioned has not been patched on upstream, the same issue should exist in PolarDB, too. If it is a problem for you, then the JIT GUC should be turned off.

**Comment by ZhangHuiGui** [comment]
> Hi @ZhangHuiGui :
> 
> PolarDB for PostgreSQL **does** use JIT, but does not modify the code of this part. As the issue you have mentioned has not been patched on upstream, the same issue should exist in PolarDB, too. If it is a problem for you, then the JIT GUC should be turned off.

Thanks for your reply! Get it.
