### ISSUE TITLE
[Question]是否支持babelfish扩展

### ISSUE THREAD

**Issue by ly303550688** [polardb/PolarDB-for-PostgreSQL#316]
如果不支持的话有没有计划增加支持？

**Comment by mrdrivingduck** [comment]
@ly303550688 This is currently not support by us, but we can consider to support it. Does your application need this extension?

**Comment by ly303550688** [comment]
我们有一些程序是基于mssql开发的，有计划迁移到pg或者polardb

**Comment by mrdrivingduck** [comment]
> 我们有一些程序是基于mssql开发的，有计划迁移到pg或者polardb

This extension is officially supported for PostgreSQL 13+, however, current version of PolarDB for PostgreSQL is based on PostgreSQL 11, so it cannot be supported now. We will consider to support it if we release higher kernel version of PolarDB for PostgreSQL. It is really a powerful extension!
