### ISSUE TITLE
[Question] Any plans for upgrading to postgresql 14+ ? 

### ISSUE THREAD

**Issue by samuel-cc-4451** [polardb/PolarDB-for-PostgreSQL#325]
Currently Polardb is based on Postgresql 11.9 which is EOL this year. 
Is there by any chance PolarDB will rebase on top of Postgresql 14+ ?

**Comment by mrdrivingduck** [comment]
@scherukutty Yes, upgrading to PostgreSQL 14+ is in our schedule.
