### ISSUE TITLE
[Bug]README.md中二维码链接失效

### ISSUE THREAD

**Issue by co63oc** [polardb/PolarDB-for-PostgreSQL#335]
**Describe the bug**
README.md中二维码链接失效

**To Reproduce**
![qrcode](https://user-images.githubusercontent.com/4617245/215642794-9c679638-4c46-4141-bf7d-8eb4267e4d24.png)

1. xxx
2. xxx
3. xxx

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7]

**Additional context**

**Comment by mrdrivingduck** [comment]
@co63oc Thanks for your notice! The QR code would be expired periodically due to unknown reason. I have updated the QR code in #336, and it should be working now.
