### ISSUE TITLE
使用Centos7搭建集群时遇到问题

### ISSUE THREAD

**Issue by Mr-Diaolvyu** [polardb/PolarDB-for-PostgreSQL#34]
请问目前是否有交流社区或者交流群。我在搭建过程中，使用pgxc_ctl -c $HOME/polardb/polardb_paxos.conf init all初始化集群时出现以下问题，是我需要自己安装pg服务吗？
![image](https://user-images.githubusercontent.com/85491700/121006533-922e7380-c7c3-11eb-8855-e29e1b1e3f70.png)

**Comment by mingzong-sdm** [comment]
@yuwei-michael  PTAL

**Comment by mingzong-sdm** [comment]
Thanks for your feedback, based on your description of this issue.  you may not set up environment variables.
You can reference to README.  I list the commands here, you can use them directly 
set up environment variables
vi ~/.bashrc
export PATH="$HOME/polardb/polardbhome/bin:$PATH"
export LD_LIBRARY_PATH="$HOME/polardb/polardbhome/lib:$LD_LIBRARY_PATH"

**Comment by Mr-Diaolvyu** [comment]
thanks，I use my pgxc_ctl.so cant init.I remove my pgxc_ctl.
