### ISSUE TITLE
[Question]请问parrellel-raft有计划开源吗 

### ISSUE THREAD

**Issue by jiangshifu** [polardb/PolarDB-for-PostgreSQL#351]
**Describe the problem**
RT
...

**Comment by mrdrivingduck** [comment]
Hi @jiangshifu.

Parallel-Raft is a storage-level design, which is not in a plan of open source. There is a paper publicly available introducing some detail about Parallel-Raft: [PolarFS: An Ultra-low Latency and Failure Resilient Distributed File System for Shared Storage Cloud Database](https://www.vldb.org/pvldb/vol11/p1849-cao.pdf).
