### ISSUE TITLE
[Question] Is it possible for  PolarFS to view the total space size and free size of the file system please?

### ISSUE THREAD

**Issue by meiq4096** [polardb/PolarDB-for-PostgreSQL#354]
**Describe the problem**

I know pfs can build a distributed file system on the shared storage using mkfs option, but I can't find the method to view the total size and free size of the file system.
Do you have any plans to do this please? 
...

**Comment by mrdrivingduck** [comment]
@meiq4096 Use the `info` command of PFS would display the usage.

**Comment by meiq4096** [comment]
> @meiq4096 Use the `info` command of PFS would display the usage.

Thank you for your reply.
Yes, You can see the file system metadata in the info parameter, but it's a little less user-friendly.  The output of df is better.

```
postgres@ddf1d8d202f1:~$ sudo pfs -C disk info nvme0n1p2
Blktag Info:
 (0)allocnode: id 0, shift 0, nchild=100, nall 256000, nfree 255643, next 0
Direntry Info:
 (0)allocnode: id 0, shift 0, nchild=100, nall 204800, nfree 204797, next 0
Inode Info:
 (0)allocnode: id 0, shift 0, nchild=100, nall 204800, nfree 204797, next 0

```

Or maybe you can refer to the output of "hadoop dfsadmin -report " .

![image](https://user-images.githubusercontent.com/33079488/219998328-cb188aa6-e8a4-41e2-ba2c-3e5c063d37b7.png)

**Comment by mrdrivingduck** [comment]
@meiq4096 Good suggestion!
