### ISSUE TITLE
麻烦增加Dockerfile吧

### ISSUE THREAD

**Issue by allen7lee** [polardb/PolarDB-for-PostgreSQL#363]
**Describe the problem**

能获取docker镜像，没法进行镜像定制和优化，与开源实际不符。
我们希望通过快速的镜像部署进行测试和验证，请提供，谢谢

**Comment by mrdrivingduck** [comment]
@allen7lee You can refer to the Dockerfile [here](https://apsaradb.github.io/PolarDB-for-PostgreSQL/zh/development/customize-dev-env.html).
