### ISSUE TITLE
docker部署htap实例，如何挂载数据目录，

### ISSUE THREAD

**Issue by Wangdamao01** [polardb/PolarDB-for-PostgreSQL#366]
映射目录权限777，启动报错，提示如下报错
-v /data/polardb:/home/postgres

报错
![image](https://user-images.githubusercontent.com/107663606/223368165-d986bf40-349f-4c46-82fe-e44223ce784d.png)

**Comment by Wangdamao01** [comment]
启动指令
docker run -itd  --restart=always --cap-add=SYS_PTRACE --privileged=true -p 5432:5432 -v /data/polardb:/home/postgres --name polardb_pg_htap polardb/polardb_pg_local_instance:htap bash

**Comment by mrdrivingduck** [comment]
@Wangdamao01 We have refactored the usage of our image, now you can mount an empty directory as a volume into the container, and keep this data after the container is no longer running . Refer to the document [here](https://apsaradb.github.io/PolarDB-for-PostgreSQL/zh/deploying/db-localfs.html).
