### ISSUE TITLE
docker部署htap实例postgis插件怎么装

### ISSUE THREAD

**Issue by Wangdamao01** [polardb/PolarDB-for-PostgreSQL#367]
用docker部署htap，镜像版本polardb/polardb_pg_local_instance:htap，默认没装postgis，应该怎么安装postgis插件

报错截图
![image](https://user-images.githubusercontent.com/107663606/223399318-14c7a97a-b90f-42f1-955a-d176b0167935.png)

**Comment by mrdrivingduck** [comment]
@Wangdamao01 Sorry for the late response. We have an online experiment [here](https://developer.aliyun.com/adc/scenario/59c74f426f644ad295f4d6e3e10c68d8).

**Comment by Wangdamao01** [comment]
ok, thankyou

**Comment by Wangdamao01** [comment]
I advise postgis plugin should be in the image，Avoid manual installation

**Comment by mrdrivingduck** [comment]
@Wangdamao01 We are considering to support like what you said, because it is a very import plugin in PostgreSQL.

**Comment by Wangdamao01** [comment]
How often will the new version be postgis released

**Comment by mrdrivingduck** [comment]
> How often will the new version be postgis released

@Wangdamao01 We have supported it now.
