### ISSUE TITLE
编译安装报错：fatal error: paxos.h: No such file or directory

### ISSUE THREAD

**Issue by ThinkBlue1991** [polardb/PolarDB-for-PostgreSQL#37]
环境：centos 7.6.1810
问题：编译安装执行 ./onekey.sh all时，报错如下：
```
/home/polardb/PolarDB-for-PostgreSQL-master/src/backend/polar_dma/libconsensus/polar_wrapper/polar_consensus_log.cc:21:19: fatal error: paxos.h: No such file or directory
 #include "paxos.h"
```

**Comment by ghost** [comment]
> 环境：centos 7.6.1810
> 问题：编译安装执行 ./onekey.sh all时，报错如下：
> 
> ```
> /home/polardb/PolarDB-for-PostgreSQL-master/src/backend/polar_dma/libconsensus/polar_wrapper/polar_consensus_log.cc:21:19: fatal error: paxos.h: No such file or directory
>  #include "paxos.h"
> ```

The script for the project was very badly written, and I looked at the project, It should first compile for [here](https://github.com/alibaba/PolarDB-for-PostgreSQL/tree/master/src/backend/polar_dma/libconsensus/consensus). Generating the corresponding xxx.h file and should be copied to some path, I'm still looking for the problem, the mindset exploded! 

 A lot of files, like easy_log.h, if you don't compile [here](https://github.com/alibaba/PolarDB-for-PostgreSQL/tree/master/src/backend/polar_dma/libconsensus/consensus), you won't get these files.

You should copy the files of the path 'consensus/include' to the path `libconsensus/polar_wrapper/include`.

But other errors will be found :) :-)

I choose to wait...

**Comment by mengborong** [comment]
@EthanDBer  you can pull latest code. And just run build.sh in  source code directory. If you get some errors, please post it here.

**Comment by ThinkBlue1991** [comment]
latest code has fixed the bug, Closed！
