### ISSUE TITLE
[Question] PANIC:  could not locate a valid checkpoint record

### ISSUE THREAD

**Issue by JinkaiXu** [polardb/PolarDB-for-PostgreSQL#370]
**Describe the problem**
We deployed 1 master and 2 slaves, then run TPCC workload, and added a small number of AP threads, after a period of time, the slave nodes went down and then cannot to restart, the error.log show `PANIC:  could not locate a valid checkpoint record`, could you help me to find what caused this and how to solve this problem ?
...

**Comment by mrdrivingduck** [comment]
@JinkaiXu 

On master, create a temporary slot to hold some WAL record:

```sql
SELECT pg_create_physical_replication_slot('fake_slot', true);
```

Then, try to start slave. The slave should be started. After the slave started, remove the temporary slot:

```sql
SELECT pg_drop_replication_slot('fake_slot');
```

**Comment by JinkaiXu** [comment]
> @JinkaiXu
> 
> On master, create a temporary slot to hold some WAL record:
> 
> ```sql
> SELECT pg_create_physical_replication_slot('fake_slot', true);
> ```
> 
> Then, try to start slave. The slave should be started. After the slave started, remove the temporary slot:
> 
> ```sql
> SELECT pg_drop_replication_slot('fake_slot');
> ```

thanks
