### ISSUE TITLE
[Question]  doubt in understanding restore full page snapshot function.

### ISSUE THREAD

**Issue by narendra-pradeep-4332** [polardb/PolarDB-for-PostgreSQL#380]
Was going through `polar_logindex_restore_fullpage_snapshot_if_needed` function. It makes sense for replicas to wait when a future page is read. But I couldn't find a case where a fullpage redo was done ( for me iterator always returns a NULL for lsn_info). 

The comment of this function states that it restores an old version of the page. How can this be done when we already have a future page with us? 

...

**Comment by funnyxj** [comment]
Under normal circumstances, the primary will not flush the future page to the shared storage. It will only write the future page when the master and backup replication delays are very high. If the replica reads the future page, there are two possibilities:
1. The primary writes the future page, which will be recorded in the logindex, and the replica iteration will not return null
2. The primary and replica have not established a normal replication relationship, causing the primary to think that there is no corresponding replica node. You may check whether the replication relationship is normal through select * from pg_stat_replication
