### ISSUE TITLE
相对于pg的代码改动点有哪些？

### ISSUE THREAD

**Issue by LyndonYang1024** [polardb/PolarDB-for-PostgreSQL#4]
大概看了一下相对熟悉的几个folder的code，除了distributed_txn，polar_datamax，polar_dma这三个目录，其它的目录是不是基本就是pg的code，没有改动？

**Comment by yjhjstz** [comment]
没有提供commit log 不友好。

**Comment by LyndonYang1024** [comment]
> 没有提供commit log 不友好。

确实，没commit log看不出哪里做了改动，大概看了下执行器和优化器的code，感觉基本没改，不知道是不是因为没有大的改动，所以没看到

**Comment by yuwei-michael** [comment]
Open-Polarx project will open source feautre step by step. Now main release Standlone, HA enhancement(paxos HA and  streaming HA), CTS feature ect. More feature and enhancement on optimizer and executor will release with distribute cluster soon.

**Comment by triump2020** [comment]
@yuwei-michael     The source code of paxos  seems  not  open ?

**Comment by yuwei-michael** [comment]
Hi triump2020, Yes, you are right, paxos library still not open source, we reference it's dynamic library when build paxos HA for now, since it's need more process work, we will open source it later.

**Comment by mengborong** [comment]
> @yuwei-michael The source code of paxos seems not open ?

@triump2020 the source code of consensus lib has been published. Please know it.
