### ISSUE TITLE
[Bug] PolarDB jdbc操作INTERVAL类型时驱动异常

### ISSUE THREAD

**Issue by jiangtao69039** [polardb/PolarDB-for-PostgreSQL#413]
**Describe the bug**
创建一个带有interval列类型的表,然后通过jdbc查询,会报异常.
```sql
create table test(id int,col1 interval);
```

通过jdbc驱动调用 ResultSetMetaData.getColumnType(i) 或者 ResultSet.getObject(i) 均会报 " function "nestedtable_in" does not exist 位置：49" 这个异常.

驱动里getPGtype能正常返回 interval

![image](https://github.com/ApsaraDB/PolarDB-for-PostgreSQL/assets/20572131/3348ea00-673c-4134-bf9b-6a28fbdcbf58)

但是getSQLType报错, 报错原因是 驱动执行下面的查询语句 .
```sql
SELECT typinput='array_in'::regproc OR typinput='nestedtable_in'::regproc, typtype   FROM pg_catalog.pg_type   LEFT   JOIN (select ns.oid as nspoid, ns.nspname, r.r           from pg_namespace as ns           join ( select s.r, (current_schemas(false))[s.r] as nspname                    from generate_series(1, array_upper(current_schemas(false), 1)) as s(r) ) as r          using ( nspname )        ) as sp     ON sp.nspoid = typnamespace  WHERE typname = 'interval'  ORDER BY sp.r, pg_type.oid DESC LIMIT 1
```

**Comment by mrdrivingduck** [comment]
@jiangtao69039 What version of JDBC are you using? You should use the JDBC version which is the same as PostgreSQL, because we are 100% compatible with PostgreSQL. `nestedtable_in` seems not to be a PostgreSQL proc type.

**Comment by jiangtao69039** [comment]
![image](https://github.com/ApsaraDB/PolarDB-for-PostgreSQL/assets/20572131/3349f089-6773-4c0c-8c53-6fea935ab9f7)

**Comment by jiangtao69039** [comment]
I use polardb-jdbc18.jar connect to polardb,  url  format is "jdbc:polardb://"

**Comment by jiangtao69039** [comment]
![image](https://github.com/ApsaraDB/PolarDB-for-PostgreSQL/assets/20572131/0157051f-1191-4f9e-b4be-be14e4f49ec9)

The exception is reported by the driver jar.  It is marked on the picture.

**Comment by jiangtao69039** [comment]
![image](https://github.com/ApsaraDB/PolarDB-for-PostgreSQL/assets/20572131/7dee3d59-cc48-4fef-830c-b6aeda1571c6)

**Comment by jiangtao69039** [comment]
The version detected by polardb here is 11.9, which is larger than 9.2. So 'nestedtable_in' is used here.

![image](https://github.com/ApsaraDB/PolarDB-for-PostgreSQL/assets/20572131/61cf4fc0-0d38-4941-b704-c62dd06b87b3)
![image](https://github.com/ApsaraDB/PolarDB-for-PostgreSQL/assets/20572131/485de53b-12f4-4094-bc98-786f8adc5f5b)

**Comment by mrdrivingduck** [comment]
@jiangtao69039 You should use the driver [here](https://jdbc.postgresql.org/), which is the 100% PostgreSQL driver. The *PolarDB JDBC* driver you are using is actually for PolarDB for PostgreSQL **(with Oracle Compability)**, which is not the version here.

**Comment by jiangtao69039** [comment]
Yes, the statement of the query type in the pg driver will not report an error.
But what I am wondering is why polardb has problems with polardb drivers

![image](https://github.com/ApsaraDB/PolarDB-for-PostgreSQL/assets/20572131/071ed489-410c-4deb-a1fc-c41f5b827fe7)

![image](https://github.com/ApsaraDB/PolarDB-for-PostgreSQL/assets/20572131/02d95ecb-c986-4dcd-a6f4-8ca3651c8dcf)

**Comment by mrdrivingduck** [comment]
@jiangtao69039 As you can see [here](https://help.aliyun.com/product/2249963.html):

![image](https://github.com/ApsaraDB/PolarDB-for-PostgreSQL/assets/32560442/deda1c63-0a77-4d38-9808-e373a4df8aeb)

The driver you have downloaded should come from the document of the 4th one, which is PolarDB for PostgreSQL (with Oracle Compability). And current repository contains the code of the 3rd one, which is PolarDB for PostgreSQL, 100% compact with PostgreSQL. They are different versions. For connecting to PolarDB-PG in this repository, the JDBC of PostgreSQL is just enough. The PolarDB driver you have downloaded is not 100% compact with PostgreSQL.
