### ISSUE TITLE
FATAL:  could not access file "pg_cron": No such file or directory

### ISSUE THREAD

**Issue by Mr-Diaolvyu** [polardb/PolarDB-for-PostgreSQL#42]
When initializing the database, starting the database reported an error that the file could not be accessed.But the file does exist, and the user is authorized.
![image](https://user-images.githubusercontent.com/85491700/121149530-518f3280-c875-11eb-8557-e949e451ceaf.png)

如下是路径所在目录：
![image](https://user-images.githubusercontent.com/85491700/121149717-7a172c80-c875-11eb-9e44-9a49fd404551.png)

**Comment by mingzong-sdm** [comment]
Thanks for your feedback, can you describe the operation process in detail? Based on your input, pg_corn is not installed.  you can switch to contrib/pg_corn directory, and run make&make install or refer to README to setup service.

**Comment by ThinkBlue1991** [comment]
@Mr-Diaolvyu 可以手动将contrib/pg_cron下面的sql和control拷贝到polardbhome/share/extension 下，将contrib/pg_cron下面的pg_cron.so拷贝到polardbhome/lib下，再重新执行init/start all操作

我猜测是build.sh的过程中make && make install pg_cron时出现问题

**Comment by ThinkBlue1991** [comment]
@Mr-Diaolvyu  或者直接删除poalrdbhome和data目录，然后重新执行build.sh操作

**Comment by Mr-Diaolvyu** [comment]
1、cd /data/software/
2、git clone https://github.com/alibaba/PolarDB-for-PostgreSQL.git
3、cd PolarDB-for-PostgreSQL/
4、./build.sh
5、su postgres
6、vim ~/.bashrc（LD_LIBRARY_PATH="/home/postgres/polardb/polardbhome"L/src/interfaces/libpq';export PATH="$LD_LIBRARY_PATH/bin:$PATH"）
7、scp -r ~/.bashrc postgres@DDB2:/home/postgres/ && scp -r ~/.bashrc postgres@DDB3:/home/postgres/
8、pgxc_ctl -c $HOME/polardb/polardb_paxos.conf prepare standalone（then vim polardb_paxos.conf）
9、pgxc_ctl -c $HOME/polardb/polardb_paxos.conf deploy all
10、pgxc_ctl -c $HOME/polardb/polardb_paxos.conf clean all 
11、pgxc_ctl -c $HOME/polardb/polardb_paxos.conf init all 

Now I will follow your prompts and run the command:/data/software/PolarDB-for-PostgreSQL-master/contrib/pg_cron/make && make install  。But an error is reported as follows
![图片](https://user-images.githubusercontent.com/85491700/121277655-a8434d80-c903-11eb-8842-42c037705768.png)
Is it because my source code is not in the Postgres user directory?Or use the root user when using./build.sh.I've given the directory owner of the source code to the Postgres user。

**Comment by Mr-Diaolvyu** [comment]
> 
> 
> @Mr-Diaolvyu 或者直接删除poalrdbhome和data目录，然后重新执行build.sh操作



> 
> 
> @Mr-Diaolvyu 可以手动将contrib/pg_cron下面的sql和control拷贝到polardbhome/share/extension 下，将contrib/pg_cron下面的pg_cron.so拷贝到polardbhome/lib下，再重新执行init/start all操作
> 
> 我猜测是build.sh的过程中make && make install pg_cron时出现问题

好的，我试试

**Comment by Mr-Diaolvyu** [comment]
> 
> 
> > @Mr-Diaolvyu 或者直接删除poalrdbhome和data目录，然后重新执行build.sh操作
> 
> > @Mr-Diaolvyu 可以手动将contrib/pg_cron下面的sql和control拷贝到polardbhome/share/extension 下，将contrib/pg_cron下面的pg_cron.so拷贝到polardbhome/lib下，再重新执行init/start all操作
> > 我猜测是build.sh的过程中make && make install pg_cron时出现问题
> 
> 好的，我试试

重新执行build.sh还是不行，同样会出现FATAL: could not access file "pg_cron": No such file or directory。我看了一下build的日志，看到下面这个内容，是不是我下载的源码中少了什么东西。因为服务器连接不了git，所以我是下载的zip包，然后上传服务器解压缩的。
![图片](https://user-images.githubusercontent.com/85491700/121280253-91532a00-c908-11eb-8988-0380134fcf94.png)

**Comment by ThinkBlue1991** [comment]
@Mr-Diaolvyu 把polardbhome目录删除了吗？我这边查找pgxs.mk的路径和你环境中的不同

```
[postgres@node199 PolarDB-for-PostgreSQL]$ pg_config --pgxs
/home/postgres/polardb/polardbhome/lib/pgxs/src/makefiles/pgxs.mk
[postgres@node199 PolarDB-for-PostgreSQL]$ which pg_config
~/polardb/polardbhome/bin/pg_config
```

**Comment by Mr-Diaolvyu** [comment]
> 
> 
> @先生-Diaolvyu 把polardbhome目录删除了吗？我这边查找pgxs.mk的路径和你环境中的不同
> 
> ```
> [postgres@node199 PolarDB-for-PostgreSQL]$ pg_config --pgxs
> /home/postgres/polardb/polardbhome/lib/pgxs/src/makefiles/pgxs.mk
> [postgres@node199 PolarDB-for-PostgreSQL]$ which pg_config
> ~/polardb/polardbhome/bin/pg_config
> ```

bulid前删了polardbhome目录了。bulid后又出现了这个目录，但是我的路径只到lib，后面的postgresql是没有的。这个是要配置文件里改吗？
[postgres@DDB1 ~]$>pg_config --pgxs
/home/postgres/polardb/polardbhome/lib/postgresql/pgxs/src/makefiles/pgxs.mk
[postgres@DDB1 ~]$>which pg_config
~/polardb/polardbhome/bin/pg_config
[postgres@DDB1 ~]$>cd /home/postgres/polardb/polardbhome/lib/postgresql/pgxs/src/makefiles/
bash: cd: /home/postgres/polardb/polardbhome/lib/postgresql/pgxs/src/makefiles/: No such file or directory
[postgres@DDB1 ~]$>cd /home/postgres/polardb/polardbhome/lib/

**Comment by yuwei-michael** [comment]
问题已经修正了。请下载代码再试试看，多谢！

**Comment by ThinkBlue1991** [comment]
> > @先生-Diaolvyu 把polardbhome目录删除了吗？我这边查找pgxs.mk的路径和你环境中的不同
> > ```
> > [postgres@node199 PolarDB-for-PostgreSQL]$ pg_config --pgxs
> > /home/postgres/polardb/polardbhome/lib/pgxs/src/makefiles/pgxs.mk
> > [postgres@node199 PolarDB-for-PostgreSQL]$ which pg_config
> > ~/polardb/polardbhome/bin/pg_config
> > ```
> 
> bulid前删了polardbhome目录了。bulid后又出现了这个目录，但是我的路径只到lib，后面的postgresql是没有的。这个是要配置文件里改吗？
> [postgres@DDB1 ~]$>pg_config --pgxs
> /home/postgres/polardb/polardbhome/lib/postgresql/pgxs/src/makefiles/pgxs.mk
> [postgres@DDB1 ~]$>which pg_config
> ~/polardb/polardbhome/bin/pg_config
> [postgres@DDB1 ~]$>cd /home/postgres/polardb/polardbhome/lib/postgresql/pgxs/src/makefiles/
> bash: cd: /home/postgres/polardb/polardbhome/lib/postgresql/pgxs/src/makefiles/: No such file or directory
> [postgres@DDB1 ~]$>cd /home/postgres/polardb/polardbhome/lib/

你再拉去最新的代码试一下，我昨天上午遇到过，可能是重新pull了一下代码

**Comment by yuwei-michael** [comment]
> > > @先生-Diaolvyu 把polardbhome目录删除了吗？我这边查找pgxs.mk的路径和你环境中的不同
> > > ```
> > > [postgres@node199 PolarDB-for-PostgreSQL]$ pg_config --pgxs
> > > /home/postgres/polardb/polardbhome/lib/pgxs/src/makefiles/pgxs.mk
> > > [postgres@node199 PolarDB-for-PostgreSQL]$ which pg_config
> > > ~/polardb/polardbhome/bin/pg_config
> > > ```
> > 
> > 
> > bulid前删了polardbhome目录了。bulid后又出现了这个目录，但是我的路径只到lib，后面的postgresql是没有的。这个是要配置文件里改吗？
> > [postgres@DDB1 ~]$>pg_config --pgxs
> > /home/postgres/polardb/polardbhome/lib/postgresqlgxs/src/makefiles/pgxs.mk
> > [postgres@DDB1 ~]$>which pg_config
> > ~/polardb/polardbhome/bin/pg_config
> > [postgres@DDB1 ~]$>cd /home/postgres/polardb/polardbhome/lib/postgresql/pgxs/src/makefiles/
> > bash: cd: /home/postgres/polardb/polardbhome/lib/postgresql/pgxs/src/makefiles/: No such file or directory
> > [postgres@DDB1 ~]$>cd /home/postgres/polardb/polardbhome/lib/
> 
> 你再拉去最新的代码试一下，我昨天上午遇到过，可能是重新pull了一下代码

你可以看下PATH和LIB环境变量中，是否还包含了其他的postgres相关路径，如果包含了，请删除后重新试下，这些路径可能是你之前在bash_profile或者bashrc中。

**Comment by Mr-Diaolvyu** [comment]
> 
> 
> > > @先生-Diaolvyu 把polardbhome目录删除了吗？我这边查找pgxs.mk的路径和你环境中的不同
> > > ```
> > > [postgres@node199 PolarDB-for-PostgreSQL]$ pg_config --pgxs
> > > /home/postgres/polardb/polardbhome/lib/pgxs/src/makefiles/pgxs.mk
> > > [postgres@node199 PolarDB-for-PostgreSQL]$ which pg_config
> > > ~/polardb/polardbhome/bin/pg_config
> > > ```
> > 
> > 
> > bulid前删了polardbhome目录了。bulid后又出现了这个目录，但是我的路径只到lib，后面的postgresql是没有的。这个是要配置文件里改吗？
> > [postgres@DDB1 ~]$>pg_config --pgxs
> > /home/postgres/polardb/polardbhome/lib/postgresql/pgxs/src/makefiles/pgxs.mk
> > [postgres@DDB1 ~]$>which pg_config
> > ~/polardb/polardbhome/bin/pg_config
> > [postgres@DDB1 ~]$>cd /home/postgres/polardb/polardbhome/lib/postgresql/pgxs/src/makefiles/
> > bash: cd: /home/postgres/polardb/polardbhome/lib/postgresql/pgxs/src/makefiles/: No such file or directory
> > [postgres@DDB1 ~]$>cd /home/postgres/polardb/polardbhome/lib/
> 
> 你再拉去最新的代码试一下，我昨天上午遇到过，可能是重新pull了一下代码

重新拉了一下代码，上面的问题解决了。但是出现了允许远程连接被拒绝的情况


> 
> 
> > > > @先生-Diaolvyu 把polardbhome目录删除了吗？我这边查找pgxs.mk的路径和你环境中的不同 
> > > > ```
> > > > [postgres@node199 PolarDB-for-PostgreSQL]$ pg_config --pgxs
> > > > /home/postgres/polardb/polardbhome/lib/pgxs/src/makefiles/pgxs.mk
> > > > [postgres@node199 PolarDB-for-PostgreSQL]$ which pg_config
> > > > ~/polardb/polardbhome/bin/pg_config
> > > > ```
> > > 
> > > 
> > > bulid前删了polardbhome目录了。bulid后又出现了这个目录，但是我的路径只到lib，后面的postgresql是没有的。这个是要配置文件里改吗？ 
> > > [postgres@DDB1 ~]$>pg_config --pgxs 
> > > /home/postgres/polardb/polardbhome/lib/postgresqlgxs/src/makefiles/pgxs.mk 
> > > [postgres@DDB1 ~]$>which pg_config 
> > > ~/polardb/polardbhome/bin/pg_config 
> > > [postgres@DDB1 ~]$>cd /home/postgres/polardb/polardbhome/lib/postgresql/pgxs/src/makefiles/ 
> > > bash: cd: /home/postgres/polardb/polardbhome/lib/postgresql/pgxs/src/makefiles/: No such file or directory 
> > > [postgres@DDB1 ~]$>cd /home/postgres/polardb/polardbhome/lib/
> > 
> > 
> > 你再拉去最新的代码试一下，我昨天上午遇到过，可能是重新pull了一下代码
> 
> 你可以看下PATH和LIB环境变量中，是否还包含了其他的postgres相关路径，如果包含了，请删除后重新试下，这些路径可能是你之前在bash_profile或者bashrc中。



> 
> 
> > > > @先生-Diaolvyu 把polardbhome目录删除了吗？我这边查找pgxs.mk的路径和你环境中的不同 
> > > > ```
> > > > [postgres@node199 PolarDB-for-PostgreSQL]$ pg_config --pgxs
> > > > /home/postgres/polardb/polardbhome/lib/pgxs/src/makefiles/pgxs.mk
> > > > [postgres@node199 PolarDB-for-PostgreSQL]$ which pg_config
> > > > ~/polardb/polardbhome/bin/pg_config
> > > > ```
> > > 
> > > 
> > > bulid前删了polardbhome目录了。bulid后又出现了这个目录，但是我的路径只到lib，后面的postgresql是没有的。这个是要配置文件里改吗？ 
> > > [postgres@DDB1 ~]$>pg_config --pgxs 
> > > /home/postgres/polardb/polardbhome/lib/postgresqlgxs/src/makefiles/pgxs.mk 
> > > [postgres@DDB1 ~]$>which pg_config 
> > > ~/polardb/polardbhome/bin/pg_config 
> > > [postgres@DDB1 ~]$>cd /home/postgres/polardb/polardbhome/lib/postgresql/pgxs/src/makefiles/ 
> > > bash: cd: /home/postgres/polardb/polardbhome/lib/postgresql/pgxs/src/makefiles/: No such file or directory 
> > > [postgres@DDB1 ~]$>cd /home/postgres/polardb/polardbhome/lib/
> > 
> > 
> > 你再拉去最新的代码试一下，我昨天上午遇到过，可能是重新pull了一下代码
> 
> 你可以看下PATH和LIB环境变量中，是否还包含了其他的postgres相关路径，如果包含了，请删除后重新试下，这些路径可能是你之前在bash_profile或者bashrc中。

The PG service started successfully, but there was an error with unauthorized remote access.This is the pg_hba.conf file that I modified myself, or it should be modified by the build script.
![图片](https://user-images.githubusercontent.com/85491700/121287462-2c053600-c914-11eb-841d-d425ff9a85ff.png)

**Comment by Mr-Diaolvyu** [comment]
> 
> 
> > > @先生-Diaolvyu 把polardbhome目录删除了吗？我这边查找pgxs.mk的路径和你环境中的不同 
> > > ```
> > > [postgres@node199 PolarDB-for-PostgreSQL]$ pg_config --pgxs
> > > /home/postgres/polardb/polardbhome/lib/pgxs/src/makefiles/pgxs.mk
> > > [postgres@node199 PolarDB-for-PostgreSQL]$ which pg_config
> > > ~/polardb/polardbhome/bin/pg_config
> > > ```
> > 
> > 
> > bulid前删了polardbhome目录了。bulid后又出现了这个目录，但是我的路径只到lib，后面的postgresql是没有的。这个是要配置文件里改吗？ 
> > [postgres@DDB1 ~]$>pg_config --pgxs 
> > /home/postgres/polardb/polardbhome/lib/postgresql/pgxs/src/makefiles/pgxs.mk 
> > [postgres@DDB1 ~]$>which pg_config 
> > ~/polardb/polardbhome/bin/pg_config 
> > [postgres@DDB1 ~]$>cd /home/postgres/polardb/polardbhome/lib/postgresql/pgxs/src/makefiles/ 
> > bash: cd: /home/postgres/polardb/polardbhome/lib/postgresql/pgxs/src/makefiles/: No such file or directory 
> > [postgres@DDB1 ~]$>cd /home/postgres/polardb/polardbhome/lib/
> 
> 你再拉去最新的代码试一下，我昨天上午遇到过，可能是重新pull了一下代码

重新拉取了代码后pg服务起来了，但是pg_hba.conf未授权ip登录。这个我自己在pg_hba.conf里修改吗？
![图片](https://user-images.githubusercontent.com/85491700/121287547-5820b700-c914-11eb-8b72-a720e5b70435.png)

**Comment by yuwei-michael** [comment]
> > > > @先生-Diaolvyu 把polardbhome目录删除了吗？我这边查找pgxs.mk的路径和你环境中的不同
> > > > ```
> > > > [postgres@node199 PolarDB-for-PostgreSQL]$ pg_config --pgxs
> > > > /home/postgres/polardb/polardbhome/lib/pgxs/src/makefiles/pgxs.mk
> > > > [postgres@node199 PolarDB-for-PostgreSQL]$ which pg_config
> > > > ~/polardb/polardbhome/bin/pg_config
> > > > ```
> > > 
> > > 
> > > bulid前删了polardbhome目录了。bulid后又出现了这个目录，但是我的路径只到lib，后面的postgresql是没有的。这个是要配置文件里改吗？
> > > [postgres@DDB1 ~]$>pg_config --pgxs
> > > /home/postgres/polardb/polardbhome/lib/postgresql/pgxs/src/makefiles/pgxs.mk
> > > [postgres@DDB1 ~]$>which pg_config
> > > ~/polardb/polardbhome/bin/pg_config
> > > [postgres@DDB1 ~]$>cd /home/postgres/polardb/polardbhome/lib/postgresql/pgxs/src/makefiles/
> > > bash: cd: /home/postgres/polardb/polardbhome/lib/postgresql/pgxs/src/makefiles/: No such file or directory
> > > [postgres@DDB1 ~]$>cd /home/postgres/polardb/polardbhome/lib/
> > 
> > 
> > 你再拉去最新的代码试一下，我昨天上午遇到过，可能是重新pull了一下代码
> 
> 重新拉取了代码后pg服务起来了，但是pg_hba.conf未授权ip登录。这个我自己在pg_hba.conf里修改吗？
> ![图片](https://user-images.githubusercontent.com/85491700/121287547-5820b700-c914-11eb-8b72-a720e5b70435.png)

这个问题应该是没有配置互信导致的，请查看readme中，关于’set up authorized key for fast access ‘部分。

**Comment by Mr-Diaolvyu** [comment]
> 
> 
> > > > > @先生-Diaolvyu 把polardbhome目录删除了吗？我这边查找pgxs.mk的路径和你环境中的不同 
> > > > > ```
> > > > > [postgres@node199 PolarDB-for-PostgreSQL]$ pg_config --pgxs
> > > > > /home/postgres/polardb/polardbhome/lib/pgxs/src/makefiles/pgxs.mk
> > > > > [postgres@node199 PolarDB-for-PostgreSQL]$ which pg_config
> > > > > ~/polardb/polardbhome/bin/pg_config
> > > > > ```
> > > > 
> > > > 
> > > > bulid前删了polardbhome目录了。bulid后又出现了这个目录，但是我的路径只到lib，后面的postgresql是没有的。这个是要配置文件里改吗？ 
> > > > [postgres@DDB1 ~]$>pg_config --pgxs 
> > > > /home/postgres/polardb/polardbhome/lib/postgresql/pgxs/src/makefiles/pgxs.mk 
> > > > [postgres@DDB1 ~]$>which pg_config 
> > > > ~/polardb/polardbhome/bin/pg_config 
> > > > [postgres@DDB1 ~]$>cd /home/postgres/polardb/polardbhome/lib/postgresql/pgxs/src/makefiles/ 
> > > > bash: cd: /home/postgres/polardb/polardbhome/lib/postgresql/pgxs/src/makefiles/: No such file or directory 
> > > > [postgres@DDB1 ~]$>cd /home/postgres/polardb/polardbhome/lib/
> > > 
> > > 
> > > 你再拉去最新的代码试一下，我昨天上午遇到过，可能是重新pull了一下代码
> > 
> > 
> > 重新拉取了代码后pg服务起来了，但是pg_hba.conf未授权ip登录。这个我自己在pg_hba.conf里修改吗？ 
> > ![图片](https://user-images.githubusercontent.com/85491700/121287547-5820b700-c914-11eb-8b72-a720e5b70435.png)
> 
> 这个问题应该是没有配置互信导致的，请查看readme中，关于’set up authorized key for fast access ‘部分。

ssh我已经配置了，且可以使用ssh+服务器名互相免密登录。这个问题以前在部署原生postgresql时遇到过，在pg_hba.conf这个配置文件中加入host    all    all    0.0.0.0/0    md5即可。但是在您的开源项目中如果我自己去加了这个配置，再执行init就会告诉我节点数据库已经启动，但是查看集群状态则显示datanode未启动。如果先执行clearn再执行init，又会把pg_hba.conf改回去。

**Comment by yuwei-michael** [comment]
简单的pghba 可以这样配置：
datanodePgHbaEntries=(10.228.0.0/25)  #可以加多行
datanodeExtraPgHba=none     # 额外的 pg_hba.conf。 

复杂针对不同节点的pghba可以这样配置：
datanodeSpecificExtraPgHba=(none none)

**Comment by Mr-Diaolvyu** [comment]
集群启动成功了，谢谢
