### ISSUE TITLE
[Question] Fail to load customization postgres extension 

### ISSUE THREAD

**Issue by Zrealshadow** [polardb/PolarDB-for-PostgreSQL#471]
**Describe the problem**
I deploy the Polar-DB through docker.
In this docker development environment, I developed a postgres extension' source code.
Then through `pg_config` and `pgxs`, I can successfully install my own postgres extension.

Now I execute cmd to connect to polardb outof docker container.
`docker run -it --rm polardb/polardb_pg_local_instance psql`   
I can not execute `CREATE EXTENSION {MYEXTENSION};`
It raise
`ERROR:  could not open extension control file "/home/postgres/tmp_basedir_polardb_pg_1100_bld/share/extension/{extension}.control": No such file or directory
`

However, it I connect to polardb in docker container.
I can successfully CREATE my extension.
...

**Comment by mrdrivingduck** [comment]
@Zrealshadow Welcome your testing of PolarDB-PG.

Like you said, if you run `docker run -it --rm polardb/polardb_pg_local_instance psql`, it means that you are starting a brand new container from the image, so that there cannot be any extension you installed manually.

**Comment by Zrealshadow** [comment]
Thx, I thought it only starts a psql client.

**Comment by Zrealshadow** [comment]
Can I just use postgres psql to connect PolarDB server ?

**Comment by Zrealshadow** [comment]
> Can I just use postgres psql to connect PolarDB server ?

it's ok
