### ISSUE TITLE
[Question]Is there support for TCP instead of RDMA?

### ISSUE THREAD

**Issue by ericjest** [polardb/PolarDB-for-PostgreSQL#485]
**Describe the problem**

Hi, based on the PolarDB papers and documentation, it seems like RDMA is used to send logs and pages between the disaggregated storage and compute layers.

Is there support for using TCP instead? I am curious whether I can deploy PolarDB without access to RDMA hardware. I've looked over the documentation and can't find any clarification on this.

**Comment by mrdrivingduck** [comment]
@ericjest Sorry for the late response. Yes, you can deploy PolarDB without RDMA hardware.

1. If you just want to deploy only a primary computing node as a PostgreSQL plus, then local file system is just enough.
2. If you want to deploy a cluster with primary node and replica node, you need to deploy a shared storage, which acts as a shared block device on both computing node. The way the shared storage works as a block device depends on the storage itself, it can use RDMA, or something else.

**Comment by ericjest** [comment]
Thank you!
