### ISSUE TITLE
Failover Slot Support

### ISSUE THREAD

**Issue by Vonng** [polardb/PolarDB-for-PostgreSQL#49]
Does PolarDB support failover slot such as [Aliyun RDS for PostgreSQL](https://help.aliyun.com/document_detail/164023.htm?spm=5176.7920951.J_6776146340.6.40171293aWJzMJ)?

**Comment by mingzong-sdm** [comment]
This feature is not currently supported, please continue to pay attention.

**Comment by mrdrivingduck** [comment]
Since newer version of PolarDB is released, this issue will be closed. If you have the same question on current stable code of PolarDB, please open a new issue. Thanks~
