### ISSUE TITLE
[Bug] db log show FATAL:  unsupported frontend protocol 1234.5680: server supports 2.0 to 3.0, when I try to connect with libpg 14.5

### ISSUE THREAD

**Issue by Mr-TTWang** [polardb/PolarDB-for-PostgreSQL#495]
**Describe the bug**

**To Reproduce**
1. xxx
2. xxx
3. xxx

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7]

**Additional context**

**Comment by Mr-TTWang** [comment]
![image](https://github.com/ApsaraDB/PolarDB-for-PostgreSQL/assets/22839969/b96fd4fe-c9b9-4e9a-a21f-015aaaa81b78)

**Comment by mrdrivingduck** [comment]
@SamirWell Seems that GSS encrypted connection is supported starting from PostgreSQL 12.

![image](https://github.com/ApsaraDB/PolarDB-for-PostgreSQL/assets/32560442/72e63fe5-6ac3-4fac-b986-7ca38380d6ac)
