### ISSUE TITLE
[Question] 如何下载安装PostgreSQL 11.9 (POLARDB Database Compatible with Oracle 11.9.18)

### ISSUE THREAD

**Issue by TTonlyV5** [polardb/PolarDB-for-PostgreSQL#496]
**Describe the problem**
这里docker安装的是PostgreSQL 11.9 (POLARDB 11.9)，如何安装PostgreSQL 11.9 (POLARDB Database Compatible with Oracle 11.9.18)
...
另钉钉群怎么加，二维码过期，没有查找加入

**Comment by mrdrivingduck** [comment]
@TTonlyV5 The repository contains PolarDB for PostgreSQL, which is 100% compatible with PostgreSQL, not PolarDB for PostgreSQL compatible with Oracle. That is two version.

This is the QR code:

![image](https://github.com/ApsaraDB/PolarDB-for-PostgreSQL/assets/32560442/2599b2c9-22aa-44ff-a419-6c96181f4fae)
