### ISSUE TITLE
PolarDB-for-PostgreSQL 是否支持pgsql的相关插件，例如时序插件timescaledb

### ISSUE THREAD

**Issue by OpenSourceApp-coder** [polardb/PolarDB-for-PostgreSQL#520]
[PolarDB-for-PostgreSQL](https://github.com/ApsaraDB/PolarDB-for-PostgreSQL) 
是否支持pgsql的相关插件，例如时序插件timescaledb

我安装的版本是：
PostgreSQL 11.9 (POLARDB 11.9)   
timescaledb-tsl-2.3.1

启用插件时提示：
 could not load library "/u01/polardb_pg/lib/timescaledb-tsl-2.3.1.so": /u01/polardb_pg/lib/timescaledb-tsl-2.3.1.so: undefined symbol: __builtin_sub_overflow

**Comment by mrdrivingduck** [comment]
Close as of fixed.
