### ISSUE TITLE
[Question]polardb_pg_local_instance:15的默认数据库和密码是多少

### ISSUE THREAD

**Issue by cfires** [polardb/PolarDB-for-PostgreSQL#536]
**Describe the problem**

Docker中polardb_pg_local_instance:15的默认数据库和密码是多少

**Comment by mrdrivingduck** [comment]
@cfires The default database is `postgres`. User and password can be specified. Refer to: https://apsaradb.github.io/PolarDB-for-PostgreSQL/zh/deploying/db-localfs.html#%E5%88%9D%E5%A7%8B%E5%8C%96%E6%95%B0%E6%8D%AE%E5%BA%93
