### ISSUE TITLE
[Question] Debian Support

### ISSUE THREAD

**Issue by Vonng** [polardb/PolarDB-for-PostgreSQL#543]
**Describe the problem**

有计划提供对 Debian （12 bookworm） 的支持吗？提供 Debian DEB 软件包。

**Comment by mrdrivingduck** [comment]
@Vonng We will look into this recently.

**Comment by mrdrivingduck** [comment]
@Vonng supported by #549, will publish new packages at next release.

**Comment by Vonng** [comment]
impressive 👍
