### ISSUE TITLE
PolarDB:15 能增加vector插件的支持吗，目前好像是不支持的。

### ISSUE THREAD

**Issue by hecor** [polardb/PolarDB-for-PostgreSQL#544]
**Describe the problem**

...

**Comment by mrdrivingduck** [comment]
@hecor v15 has already supported pgvector extension. However, I happen to find an issue which will not make it useable. Will fix it recently.

**Comment by mrdrivingduck** [comment]
Fixed by #547

**Comment by hecor** [comment]
> @hecor v15 has already supported pgvector extension. However, I happen to find an issue which will not make it useable. Will fix it recently.

Thanks for your reply, Could you tell me how to enable the pgvector extension in polardb?

**Comment by mrdrivingduck** [comment]
@hecor Follow the guide to run a container like [this](http://polardb-pg.alibaba.net/PolarDB-for-PostgreSQL/zh/), and run:

```sql
CREATE EXTENSION vector;
```

We will release new RPM packages with this fix later.
