### ISSUE TITLE
Remove "main" branch since you have "master" branch

### ISSUE THREAD

**Issue by Sunt-ing** [polardb/PolarDB-for-PostgreSQL#7]
The "main" branch generated by Github is useless since you have "master" branch.

**Comment by davidfetter** [comment]
The right thing to do here is to remove (or rename) "master."

**Comment by Sunt-ing** [comment]
@davidfetter Yes, evidently you are right. We should keep only one branch and “main” is a better name than “master”.

**Comment by yuwei-michael** [comment]
Thank you for suggestion, Fix Done.

**Comment by microcai** [comment]
咋的在中国的地盘上也玩黑命贵了？

**Comment by Sunt-ing** [comment]
> 咋的在中国的地盘上也玩黑命贵了？

If this repository is gonna international, respecting some common rules is as significant as writing docs and comments in English. However, the maintainers are responsible for how to deal with this issue.  We just give some advice.

**Comment by microcai** [comment]
> > 咋的在中国的地盘上也玩黑命贵了？
> 
> If this repository is gonna international, respecting some common rules is as significant as writing docs and comments in English. However, the maintainers are responsible for how to deal with this issue. We just give some advice.

至少　74216154　的美国人不同意你的观点。只有81268924　个美国人会认同黑人的命比他们的贵。

**Comment by Sunt-ing** [comment]
> > > 咋的在中国的地盘上也玩黑命贵了？
> > 
> > 
> > If this repository is gonna international, respecting some common rules is as significant as writing docs and comments in English. However, the maintainers are responsible for how to deal with this issue. We just give some advice.
> 
> 至少　74216154　的美国人不同意你的观点。只有 81268924　个美国人会认同黑人的命比他们的贵。

1. Choosing the "main" branch doesn't mean that black lives more matter than others.  Your comments make no sense.
2. Choosing the "master" branch is OK if the maintainers think renaming a branch is expensive. 
3. This's the final comment from me on this issue.

**Comment by microcai** [comment]
ｍａｓｔｅｒ　用的好好的，不是黑命贵，没事折腾啥改名？

**Comment by yuwei-michael** [comment]
We will keep master branch  and delete main branch based on our habits. And PG community also use master branch. Thank you for Sunt-ing, davidfetter,  microcai 's suggestion, if keep both master and main, may let some people to confuse which one is most important branch.
