### ISSUE TITLE
Thread Pool solves the problem of large concurrent connection performance

### ISSUE THREAD

**Issue by digoal** [polardb/PolarDB-for-PostgreSQL#75]
Thread Pool solves the problem of large concurrent connection performance, similar to the Oracle Shared Server pattern.
Currently, PG is a process model, and each session corresponds to 1 connection. When concurrency is very large, the overhead of process management will gradually rise, seriously affecting performance.

**Comment by polardb-open** [comment]
Yes. We probably faced similar concurrency issues for either thread based or process based connection pooling. This change needs to be conducted thoroughly. Our target is to upgrade with PG easily, such as through extension.  Connection pooling may require changes of backend architecture. Let's keep this idea and come back to it later.
