### ISSUE TITLE
Persisting the shared buffer pool so that hot tables are not squeezed out of the buffer

### ISSUE THREAD

**Issue by digoal** [polardb/PolarDB-for-PostgreSQL#79]
Support persisting the shared buffer pool so that hot tables are not squeezed out of the buffer

**Comment by polardb-open** [comment]
Let me try to understand your suggestion: build some swap space like mechanism for PG shared buffer pool, so that some dirty buffers are written to swap space and they can be used for hot tables? Why not directly writing them out to their tables in disk?

**Comment by digoal** [comment]
Add a keep buffer pool , which is different from the shared buffer pool in that the data in the keep buffer pool is manually specified by the DBA and is not affected by the shared buffer pool LRU algorithm. To solve the problem that frequently queried hot tables data may be eliminated in the shared buffer pool when running big query.

Keep buffer pool is only one solution, and I think there may be other solutions to solve this problem.
