### ISSUE TITLE
DMA library catalog contains compiled binaries

### ISSUE THREAD

**Issue by darthunix** [polardb/PolarDB-for-PostgreSQL#9]
I've tried to build PolarDB on MacOS but failed because of the linking problems  with pre-compiled DMA [libraries](https://github.com/alibaba/PolarDB-for-PostgreSQL/tree/master/src/backend/polar_dma/lib) (for Linux I suppose). Can you replace it with the source code and fix the [Makefile](https://github.com/alibaba/PolarDB-for-PostgreSQL/blob/master/src/backend/polar_dma/Makefile) (at the moment it simply copies the binaries)?

**Comment by danolivo** [comment]
I see only one problem with build under MacOS 14.5 - usage of deprecated OpenSSL functions (that you can use with openssl1.0) that don't exists in openssl1.1.

**Comment by mengborong** [comment]
The DMA consensus library is not supported on MacOS. We will replace the dynamic library with source code soon.  The OpenSSL version which  consensus library depend on is 1.0.2k. Thanks for your attension.

**Comment by mengborong** [comment]
Hi, @darthunix @danolivo . consensus dynamic lib has been replaced by source code. When running build.sh on top directory, it will be rebuilt. Please see https://github.com/alibaba/PolarDB-for-PostgreSQL#deployment-from-source-code for dependency.
But it has not been supported on MacOS yet. You can try to build PolarDB in docker if the CPU is x86.

**Comment by mrdrivingduck** [comment]
Since newer version of PolarDB is released, this issue will be closed. If you have the same question on current stable code of PolarDB, please open a new issue. Thanks~
